// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: candles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countCandlesByPeriod = `-- name: CountCandlesByPeriod :one
SELECT COUNT(*) FROM normalized_candles
WHERE exchange = $1 AND symbol = $2 AND period = $3
  AND timestamp >= $4 AND timestamp <= $5
`

type CountCandlesByPeriodParams struct {
	Exchange    string `db:"exchange" json:"exchange"`
	Symbol      string `db:"symbol" json:"symbol"`
	Period      string `db:"period" json:"period"`
	Timestamp   int64  `db:"timestamp" json:"timestamp"`
	Timestamp_2 int64  `db:"timestamp_2" json:"timestamp_2"`
}

func (q *Queries) CountCandlesByPeriod(ctx context.Context, arg CountCandlesByPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCandlesByPeriod,
		arg.Exchange,
		arg.Symbol,
		arg.Period,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCandles = `-- name: GetCandles :many
SELECT symbol, exchange, trade_type, period, timestamp,
       open, high, low, close, volume, buy_volume,
       COALESCE(symbol_family, '') as symbol_family
FROM normalized_candles
WHERE exchange = $1 AND symbol = $2 AND period = $3
  AND timestamp >= $4 AND timestamp <= $5
ORDER BY timestamp DESC
LIMIT $6
`

type GetCandlesParams struct {
	Exchange    string `db:"exchange" json:"exchange"`
	Symbol      string `db:"symbol" json:"symbol"`
	Period      string `db:"period" json:"period"`
	Timestamp   int64  `db:"timestamp" json:"timestamp"`
	Timestamp_2 int64  `db:"timestamp_2" json:"timestamp_2"`
	Limit       int32  `db:"limit" json:"limit"`
}

type GetCandlesRow struct {
	Symbol       string          `db:"symbol" json:"symbol"`
	Exchange     string          `db:"exchange" json:"exchange"`
	TradeType    string          `db:"trade_type" json:"trade_type"`
	Period       string          `db:"period" json:"period"`
	Timestamp    int64           `db:"timestamp" json:"timestamp"`
	Open         decimal.Decimal `db:"open" json:"open"`
	High         decimal.Decimal `db:"high" json:"high"`
	Low          decimal.Decimal `db:"low" json:"low"`
	Close        decimal.Decimal `db:"close" json:"close"`
	Volume       decimal.Decimal `db:"volume" json:"volume"`
	BuyVolume    decimal.Decimal `db:"buy_volume" json:"buy_volume"`
	SymbolFamily string          `db:"symbol_family" json:"symbol_family"`
}

func (q *Queries) GetCandles(ctx context.Context, arg GetCandlesParams) ([]GetCandlesRow, error) {
	rows, err := q.db.Query(ctx, getCandles,
		arg.Exchange,
		arg.Symbol,
		arg.Period,
		arg.Timestamp,
		arg.Timestamp_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCandlesRow{}
	for rows.Next() {
		var i GetCandlesRow
		if err := rows.Scan(
			&i.Symbol,
			&i.Exchange,
			&i.TradeType,
			&i.Period,
			&i.Timestamp,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.BuyVolume,
			&i.SymbolFamily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCandle = `-- name: GetLatestCandle :one
SELECT symbol, exchange, trade_type, period, timestamp,
       open, high, low, close, volume, buy_volume,
       COALESCE(symbol_family, '') as symbol_family
FROM normalized_candles
WHERE exchange = $1 AND symbol = $2 AND trade_type = $3 AND period = $4
ORDER BY timestamp DESC
LIMIT 1
`

type GetLatestCandleParams struct {
	Exchange  string `db:"exchange" json:"exchange"`
	Symbol    string `db:"symbol" json:"symbol"`
	TradeType string `db:"trade_type" json:"trade_type"`
	Period    string `db:"period" json:"period"`
}

type GetLatestCandleRow struct {
	Symbol       string          `db:"symbol" json:"symbol"`
	Exchange     string          `db:"exchange" json:"exchange"`
	TradeType    string          `db:"trade_type" json:"trade_type"`
	Period       string          `db:"period" json:"period"`
	Timestamp    int64           `db:"timestamp" json:"timestamp"`
	Open         decimal.Decimal `db:"open" json:"open"`
	High         decimal.Decimal `db:"high" json:"high"`
	Low          decimal.Decimal `db:"low" json:"low"`
	Close        decimal.Decimal `db:"close" json:"close"`
	Volume       decimal.Decimal `db:"volume" json:"volume"`
	BuyVolume    decimal.Decimal `db:"buy_volume" json:"buy_volume"`
	SymbolFamily string          `db:"symbol_family" json:"symbol_family"`
}

func (q *Queries) GetLatestCandle(ctx context.Context, arg GetLatestCandleParams) (GetLatestCandleRow, error) {
	row := q.db.QueryRow(ctx, getLatestCandle,
		arg.Exchange,
		arg.Symbol,
		arg.TradeType,
		arg.Period,
	)
	var i GetLatestCandleRow
	err := row.Scan(
		&i.Symbol,
		&i.Exchange,
		&i.TradeType,
		&i.Period,
		&i.Timestamp,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.BuyVolume,
		&i.SymbolFamily,
	)
	return i, err
}

const getMissingPeriods = `-- name: GetMissingPeriods :many
WITH expected AS (
    SELECT generate_series($4::bigint, $5::bigint, $6::bigint) AS ts
)
SELECT e.ts
FROM expected e
LEFT JOIN normalized_candles nc
    ON nc.exchange = $1
    AND nc.symbol = $2
    AND nc.trade_type = $3
    AND nc.period = $7
    AND nc.timestamp = e.ts
WHERE nc.id IS NULL
ORDER BY e.ts
`

type GetMissingPeriodsParams struct {
	Exchange  string `db:"exchange" json:"exchange"`
	Symbol    string `db:"symbol" json:"symbol"`
	TradeType string `db:"trade_type" json:"trade_type"`
	Column4   int64  `db:"column_4" json:"column_4"`
	Column5   int64  `db:"column_5" json:"column_5"`
	Column6   int64  `db:"column_6" json:"column_6"`
	Period    string `db:"period" json:"period"`
}

func (q *Queries) GetMissingPeriods(ctx context.Context, arg GetMissingPeriodsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, getMissingPeriods,
		arg.Exchange,
		arg.Symbol,
		arg.TradeType,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Period,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ts int64
		if err := rows.Scan(&ts); err != nil {
			return nil, err
		}
		items = append(items, ts)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCandle = `-- name: InsertCandle :exec
INSERT INTO normalized_candles (
    symbol, exchange, trade_type, period, timestamp,
    open, high, low, close, volume, buy_volume, symbol_family
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (symbol, exchange, trade_type, period, timestamp)
DO UPDATE SET
    open = EXCLUDED.open,
    high = EXCLUDED.high,
    low = EXCLUDED.low,
    close = EXCLUDED.close,
    volume = EXCLUDED.volume,
    buy_volume = EXCLUDED.buy_volume
`

type InsertCandleParams struct {
	Symbol       string          `db:"symbol" json:"symbol"`
	Exchange     string          `db:"exchange" json:"exchange"`
	TradeType    string          `db:"trade_type" json:"trade_type"`
	Period       string          `db:"period" json:"period"`
	Timestamp    int64           `db:"timestamp" json:"timestamp"`
	Open         decimal.Decimal `db:"open" json:"open"`
	High         decimal.Decimal `db:"high" json:"high"`
	Low          decimal.Decimal `db:"low" json:"low"`
	Close        decimal.Decimal `db:"close" json:"close"`
	Volume       decimal.Decimal `db:"volume" json:"volume"`
	BuyVolume    decimal.Decimal `db:"buy_volume" json:"buy_volume"`
	SymbolFamily pgtype.Text     `db:"symbol_family" json:"symbol_family"`
}

func (q *Queries) InsertCandle(ctx context.Context, arg InsertCandleParams) error {
	_, err := q.db.Exec(ctx, insertCandle,
		arg.Symbol,
		arg.Exchange,
		arg.TradeType,
		arg.Period,
		arg.Timestamp,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
		arg.BuyVolume,
		arg.SymbolFamily,
	)
	return err
}
