// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: partition.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPartitionByYear = `-- name: GetPartitionByYear :one
SELECT table_name, year, created_at
FROM partition_registry
WHERE year = $1
`

type GetPartitionByYearRow struct {
	TableName string           `db:"table_name" json:"table_name"`
	Year      int32            `db:"year" json:"year"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetPartitionByYear(ctx context.Context, year int32) (GetPartitionByYearRow, error) {
	row := q.db.QueryRow(ctx, getPartitionByYear, year)
	var i GetPartitionByYearRow
	err := row.Scan(&i.TableName, &i.Year, &i.CreatedAt)
	return i, err
}

const getPartitionRegistry = `-- name: GetPartitionRegistry :many
SELECT table_name, year, created_at
FROM partition_registry
ORDER BY year
`

type GetPartitionRegistryRow struct {
	TableName string           `db:"table_name" json:"table_name"`
	Year      int32            `db:"year" json:"year"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetPartitionRegistry(ctx context.Context) ([]GetPartitionRegistryRow, error) {
	rows, err := q.db.Query(ctx, getPartitionRegistry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPartitionRegistryRow{}
	for rows.Next() {
		var i GetPartitionRegistryRow
		if err := rows.Scan(&i.TableName, &i.Year, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPartitionRegistry = `-- name: InsertPartitionRegistry :exec
INSERT INTO partition_registry (table_name, year)
VALUES ($1, $2)
ON CONFLICT (table_name) DO NOTHING
`

type InsertPartitionRegistryParams struct {
	TableName string `db:"table_name" json:"table_name"`
	Year      int32  `db:"year" json:"year"`
}

func (q *Queries) InsertPartitionRegistry(ctx context.Context, arg InsertPartitionRegistryParams) error {
	_, err := q.db.Exec(ctx, insertPartitionRegistry, arg.TableName, arg.Year)
	return err
}
