// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountCandlesByPeriod(ctx context.Context, arg CountCandlesByPeriodParams) (int64, error)
	// Delete a symbol and return for unsubscribe handling
	DeleteSymbolInfo(ctx context.Context, arg DeleteSymbolInfoParams) error
	// Delete all symbols for an exchange and trade type
	DeleteSymbolInfosByExchange(ctx context.Context, arg DeleteSymbolInfosByExchangeParams) error
	GetCandles(ctx context.Context, arg GetCandlesParams) ([]GetCandlesRow, error)
	GetLatestCandle(ctx context.Context, arg GetLatestCandleParams) (GetLatestCandleRow, error)
	GetMissingPeriods(ctx context.Context, arg GetMissingPeriodsParams) ([]int64, error)
	GetPartitionByYear(ctx context.Context, year int32) (GetPartitionByYearRow, error)
	GetPartitionRegistry(ctx context.Context) ([]GetPartitionRegistryRow, error)
	GetSymbolInfo(ctx context.Context, arg GetSymbolInfoParams) (GetSymbolInfoRow, error)
	// Get single symbol info
	GetSymbolInfoByKey(ctx context.Context, arg GetSymbolInfoByKeyParams) (GetSymbolInfoByKeyRow, error)
	GetSymbolInfos(ctx context.Context, exchange string) ([]GetSymbolInfosRow, error)
	GetSymbolSyncStatus(ctx context.Context, arg GetSymbolSyncStatusParams) (GetSymbolSyncStatusRow, error)
	// Get symbols with sync_enabled = true for WS subscription
	GetSyncEnabledSymbolInfos(ctx context.Context, exchange string) ([]GetSyncEnabledSymbolInfosRow, error)
	InsertCandle(ctx context.Context, arg InsertCandleParams) error
	InsertPartitionRegistry(ctx context.Context, arg InsertPartitionRegistryParams) error
	ListSymbolSyncStatus(ctx context.Context, exchange string) ([]ListSymbolSyncStatusRow, error)
	// Update sync_enabled flag for a symbol
	UpdateSymbolSyncEnabled(ctx context.Context, arg UpdateSymbolSyncEnabledParams) error
	// Insert new symbol or update existing (without overwriting symbol, base_currency, quote_currency)
	UpsertSymbolInfo(ctx context.Context, arg UpsertSymbolInfoParams) error
	UpsertSymbolSyncStatus(ctx context.Context, arg UpsertSymbolSyncStatusParams) error
}

var _ Querier = (*Queries)(nil)
