// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_status.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSymbolSyncStatus = `-- name: GetSymbolSyncStatus :one
SELECT exchange, symbol, trade_type, earliest_data_ts, latest_sync_ts
FROM symbol_sync_status
WHERE exchange = $1 AND symbol = $2 AND trade_type = $3
`

type GetSymbolSyncStatusParams struct {
	Exchange  string `db:"exchange" json:"exchange"`
	Symbol    string `db:"symbol" json:"symbol"`
	TradeType string `db:"trade_type" json:"trade_type"`
}

type GetSymbolSyncStatusRow struct {
	Exchange       string      `db:"exchange" json:"exchange"`
	Symbol         string      `db:"symbol" json:"symbol"`
	TradeType      string      `db:"trade_type" json:"trade_type"`
	EarliestDataTs pgtype.Int8 `db:"earliest_data_ts" json:"earliest_data_ts"`
	LatestSyncTs   pgtype.Int8 `db:"latest_sync_ts" json:"latest_sync_ts"`
}

func (q *Queries) GetSymbolSyncStatus(ctx context.Context, arg GetSymbolSyncStatusParams) (GetSymbolSyncStatusRow, error) {
	row := q.db.QueryRow(ctx, getSymbolSyncStatus, arg.Exchange, arg.Symbol, arg.TradeType)
	var i GetSymbolSyncStatusRow
	err := row.Scan(
		&i.Exchange,
		&i.Symbol,
		&i.TradeType,
		&i.EarliestDataTs,
		&i.LatestSyncTs,
	)
	return i, err
}

const listSymbolSyncStatus = `-- name: ListSymbolSyncStatus :many
SELECT exchange, symbol, trade_type, earliest_data_ts, latest_sync_ts
FROM symbol_sync_status
WHERE exchange = $1
ORDER BY symbol
`

type ListSymbolSyncStatusRow struct {
	Exchange       string      `db:"exchange" json:"exchange"`
	Symbol         string      `db:"symbol" json:"symbol"`
	TradeType      string      `db:"trade_type" json:"trade_type"`
	EarliestDataTs pgtype.Int8 `db:"earliest_data_ts" json:"earliest_data_ts"`
	LatestSyncTs   pgtype.Int8 `db:"latest_sync_ts" json:"latest_sync_ts"`
}

func (q *Queries) ListSymbolSyncStatus(ctx context.Context, exchange string) ([]ListSymbolSyncStatusRow, error) {
	rows, err := q.db.Query(ctx, listSymbolSyncStatus, exchange)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSymbolSyncStatusRow{}
	for rows.Next() {
		var i ListSymbolSyncStatusRow
		if err := rows.Scan(
			&i.Exchange,
			&i.Symbol,
			&i.TradeType,
			&i.EarliestDataTs,
			&i.LatestSyncTs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSymbolSyncStatus = `-- name: UpsertSymbolSyncStatus :exec
INSERT INTO symbol_sync_status (exchange, symbol, trade_type, earliest_data_ts, latest_sync_ts)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (exchange, symbol, trade_type)
DO UPDATE SET
    earliest_data_ts = EXCLUDED.earliest_data_ts,
    latest_sync_ts = EXCLUDED.latest_sync_ts,
    updated_at = NOW()
`

type UpsertSymbolSyncStatusParams struct {
	Exchange       string      `db:"exchange" json:"exchange"`
	Symbol         string      `db:"symbol" json:"symbol"`
	TradeType      string      `db:"trade_type" json:"trade_type"`
	EarliestDataTs pgtype.Int8 `db:"earliest_data_ts" json:"earliest_data_ts"`
	LatestSyncTs   pgtype.Int8 `db:"latest_sync_ts" json:"latest_sync_ts"`
}

func (q *Queries) UpsertSymbolSyncStatus(ctx context.Context, arg UpsertSymbolSyncStatusParams) error {
	_, err := q.db.Exec(ctx, upsertSymbolSyncStatus,
		arg.Exchange,
		arg.Symbol,
		arg.TradeType,
		arg.EarliestDataTs,
		arg.LatestSyncTs,
	)
	return err
}
