
export const ErrorCodes = {
  // 通用错误
  INVALID_PARAMS: 'INVALID_PARAMS',
  SYMBOL_NOT_AVAILABLE: 'SYMBOL_NOT_AVAILABLE',
  INVALID_TRADE_TYPE: 'INVALID_TRADE_TYPE',
  
  // 余额与仓位
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INSUFFICIENT_POSITION: 'INSUFFICIENT_POSITION',
  
  // 数量相关
  QUANTITY_TOO_SMALL: 'QUANTITY_TOO_SMALL',
  QUANTITY_TOO_LARGE: 'QUANTITY_TOO_LARGE',
  
  // 普通订单
  PLACE_ORDER_ERROR: 'PLACE_ORDER_ERROR',
  CANCEL_ORDER_ERROR: 'CANCEL_ORDER_ERROR',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INVALID_ORDER_RESPONSE: 'INVALID_ORDER_RESPONSE',
  BATCH_PLACE_ORDER_ERROR: 'BATCH_PLACE_ORDER_ERROR',
  
  // 策略订单 (止盈止损/计划委托/移动止损)
  PLACE_STRATEGY_ORDER_ERROR: 'PLACE_STRATEGY_ORDER_ERROR',
  CANCEL_STRATEGY_ORDER_ERROR: 'CANCEL_STRATEGY_ORDER_ERROR',
  STRATEGY_ORDER_NOT_FOUND: 'STRATEGY_ORDER_NOT_FOUND',
  GET_STRATEGY_ORDER_ERROR: 'GET_STRATEGY_ORDER_ERROR',
  GET_OPEN_STRATEGY_ORDERS_ERROR: 'GET_OPEN_STRATEGY_ORDERS_ERROR',
  INVALID_STRATEGY_ORDER_TYPE: 'INVALID_STRATEGY_ORDER_TYPE',
  TRIGGER_PRICE_INVALID: 'TRIGGER_PRICE_INVALID',
  
  // 市场数据
  SYMBOL_NOT_FOUND: 'SYMBOL_NOT_FOUND',
  PRICE_NOT_FOUND: 'PRICE_NOT_FOUND',
  TICKER_NOT_FOUND: 'TICKER_NOT_FOUND',
  ORDERBOOK_NOT_FOUND: 'ORDERBOOK_NOT_FOUND',
  MARK_PRICE_NOT_FOUND: 'MARK_PRICE_NOT_FOUND',
  
  // WebSocket
  WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR',
  WS_AUTHENTICATION_ERROR: 'WS_AUTHENTICATION_ERROR',
  WS_SUBSCRIPTION_ERROR: 'WS_SUBSCRIPTION_ERROR'
}
