services:
  trader-service-node:
    image: node:20-alpine
    container_name: trader-service-node
    working_dir: /data/app/trader-service-node
    environment:
      - NODE_ENV=production
    ports:
      - "9003:9003"
    volumes:
      - ./:/data/app/trader-service-node
    command: ["/bin/sh", "-c", "ls && npm run start"]
    restart: unless-stopped
    networks:
      - shared_network
networks:
  shared_network:
    external: true
