// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               v6.33.4
// source: signal.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "./google/protobuf/timestamp.js";

export const protobufPackage = "signal";

/** 信号类型 */
export enum SignalType {
  SIGNAL_TYPE_UNSPECIFIED = 0,
  /** SIGNAL_TYPE_ENTRY_LONG - 开多 */
  SIGNAL_TYPE_ENTRY_LONG = 1,
  /** SIGNAL_TYPE_ENTRY_SHORT - 开空 */
  SIGNAL_TYPE_ENTRY_SHORT = 2,
  /** SIGNAL_TYPE_EXIT_LONG - 平多 */
  SIGNAL_TYPE_EXIT_LONG = 3,
  /** SIGNAL_TYPE_EXIT_SHORT - 平空 */
  SIGNAL_TYPE_EXIT_SHORT = 4,
  /** SIGNAL_TYPE_STOP_LOSS - 止损 */
  SIGNAL_TYPE_STOP_LOSS = 5,
  /** SIGNAL_TYPE_TAKE_PROFIT - 止盈 */
  SIGNAL_TYPE_TAKE_PROFIT = 6,
  /** SIGNAL_TYPE_REBALANCE - 再平衡 */
  SIGNAL_TYPE_REBALANCE = 7,
  UNRECOGNIZED = -1,
}

export function signalTypeFromJSON(object: any): SignalType {
  switch (object) {
    case 0:
    case "SIGNAL_TYPE_UNSPECIFIED":
      return SignalType.SIGNAL_TYPE_UNSPECIFIED;
    case 1:
    case "SIGNAL_TYPE_ENTRY_LONG":
      return SignalType.SIGNAL_TYPE_ENTRY_LONG;
    case 2:
    case "SIGNAL_TYPE_ENTRY_SHORT":
      return SignalType.SIGNAL_TYPE_ENTRY_SHORT;
    case 3:
    case "SIGNAL_TYPE_EXIT_LONG":
      return SignalType.SIGNAL_TYPE_EXIT_LONG;
    case 4:
    case "SIGNAL_TYPE_EXIT_SHORT":
      return SignalType.SIGNAL_TYPE_EXIT_SHORT;
    case 5:
    case "SIGNAL_TYPE_STOP_LOSS":
      return SignalType.SIGNAL_TYPE_STOP_LOSS;
    case 6:
    case "SIGNAL_TYPE_TAKE_PROFIT":
      return SignalType.SIGNAL_TYPE_TAKE_PROFIT;
    case 7:
    case "SIGNAL_TYPE_REBALANCE":
      return SignalType.SIGNAL_TYPE_REBALANCE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SignalType.UNRECOGNIZED;
  }
}

export function signalTypeToJSON(object: SignalType): string {
  switch (object) {
    case SignalType.SIGNAL_TYPE_UNSPECIFIED:
      return "SIGNAL_TYPE_UNSPECIFIED";
    case SignalType.SIGNAL_TYPE_ENTRY_LONG:
      return "SIGNAL_TYPE_ENTRY_LONG";
    case SignalType.SIGNAL_TYPE_ENTRY_SHORT:
      return "SIGNAL_TYPE_ENTRY_SHORT";
    case SignalType.SIGNAL_TYPE_EXIT_LONG:
      return "SIGNAL_TYPE_EXIT_LONG";
    case SignalType.SIGNAL_TYPE_EXIT_SHORT:
      return "SIGNAL_TYPE_EXIT_SHORT";
    case SignalType.SIGNAL_TYPE_STOP_LOSS:
      return "SIGNAL_TYPE_STOP_LOSS";
    case SignalType.SIGNAL_TYPE_TAKE_PROFIT:
      return "SIGNAL_TYPE_TAKE_PROFIT";
    case SignalType.SIGNAL_TYPE_REBALANCE:
      return "SIGNAL_TYPE_REBALANCE";
    case SignalType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 信号来源 */
export enum SignalSource {
  SIGNAL_SOURCE_UNSPECIFIED = 0,
  /** SIGNAL_SOURCE_STRATEGY - 策略引擎 */
  SIGNAL_SOURCE_STRATEGY = 1,
  /** SIGNAL_SOURCE_RISK - 风控引擎 */
  SIGNAL_SOURCE_RISK = 2,
  /** SIGNAL_SOURCE_USER - 用户手动 */
  SIGNAL_SOURCE_USER = 3,
  /** SIGNAL_SOURCE_ADMIN - 管理员 */
  SIGNAL_SOURCE_ADMIN = 4,
  UNRECOGNIZED = -1,
}

export function signalSourceFromJSON(object: any): SignalSource {
  switch (object) {
    case 0:
    case "SIGNAL_SOURCE_UNSPECIFIED":
      return SignalSource.SIGNAL_SOURCE_UNSPECIFIED;
    case 1:
    case "SIGNAL_SOURCE_STRATEGY":
      return SignalSource.SIGNAL_SOURCE_STRATEGY;
    case 2:
    case "SIGNAL_SOURCE_RISK":
      return SignalSource.SIGNAL_SOURCE_RISK;
    case 3:
    case "SIGNAL_SOURCE_USER":
      return SignalSource.SIGNAL_SOURCE_USER;
    case 4:
    case "SIGNAL_SOURCE_ADMIN":
      return SignalSource.SIGNAL_SOURCE_ADMIN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SignalSource.UNRECOGNIZED;
  }
}

export function signalSourceToJSON(object: SignalSource): string {
  switch (object) {
    case SignalSource.SIGNAL_SOURCE_UNSPECIFIED:
      return "SIGNAL_SOURCE_UNSPECIFIED";
    case SignalSource.SIGNAL_SOURCE_STRATEGY:
      return "SIGNAL_SOURCE_STRATEGY";
    case SignalSource.SIGNAL_SOURCE_RISK:
      return "SIGNAL_SOURCE_RISK";
    case SignalSource.SIGNAL_SOURCE_USER:
      return "SIGNAL_SOURCE_USER";
    case SignalSource.SIGNAL_SOURCE_ADMIN:
      return "SIGNAL_SOURCE_ADMIN";
    case SignalSource.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 信号状态 */
export enum SignalStatus {
  SIGNAL_STATUS_UNSPECIFIED = 0,
  /** SIGNAL_STATUS_PENDING - 待处理 */
  SIGNAL_STATUS_PENDING = 1,
  /** SIGNAL_STATUS_PROCESSING - 处理中 */
  SIGNAL_STATUS_PROCESSING = 2,
  /** SIGNAL_STATUS_COMPLETED - 已完成 */
  SIGNAL_STATUS_COMPLETED = 3,
  /** SIGNAL_STATUS_REJECTED - 已拒绝 */
  SIGNAL_STATUS_REJECTED = 4,
  /** SIGNAL_STATUS_CANCELLED - 已取消 */
  SIGNAL_STATUS_CANCELLED = 5,
  UNRECOGNIZED = -1,
}

export function signalStatusFromJSON(object: any): SignalStatus {
  switch (object) {
    case 0:
    case "SIGNAL_STATUS_UNSPECIFIED":
      return SignalStatus.SIGNAL_STATUS_UNSPECIFIED;
    case 1:
    case "SIGNAL_STATUS_PENDING":
      return SignalStatus.SIGNAL_STATUS_PENDING;
    case 2:
    case "SIGNAL_STATUS_PROCESSING":
      return SignalStatus.SIGNAL_STATUS_PROCESSING;
    case 3:
    case "SIGNAL_STATUS_COMPLETED":
      return SignalStatus.SIGNAL_STATUS_COMPLETED;
    case 4:
    case "SIGNAL_STATUS_REJECTED":
      return SignalStatus.SIGNAL_STATUS_REJECTED;
    case 5:
    case "SIGNAL_STATUS_CANCELLED":
      return SignalStatus.SIGNAL_STATUS_CANCELLED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SignalStatus.UNRECOGNIZED;
  }
}

export function signalStatusToJSON(object: SignalStatus): string {
  switch (object) {
    case SignalStatus.SIGNAL_STATUS_UNSPECIFIED:
      return "SIGNAL_STATUS_UNSPECIFIED";
    case SignalStatus.SIGNAL_STATUS_PENDING:
      return "SIGNAL_STATUS_PENDING";
    case SignalStatus.SIGNAL_STATUS_PROCESSING:
      return "SIGNAL_STATUS_PROCESSING";
    case SignalStatus.SIGNAL_STATUS_COMPLETED:
      return "SIGNAL_STATUS_COMPLETED";
    case SignalStatus.SIGNAL_STATUS_REJECTED:
      return "SIGNAL_STATUS_REJECTED";
    case SignalStatus.SIGNAL_STATUS_CANCELLED:
      return "SIGNAL_STATUS_CANCELLED";
    case SignalStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 信号元数据 */
export interface SignalMetadata {
  strategyId: string;
  symbol: string;
  exchange: string;
  tags: { [key: string]: string };
  notes: string;
}

export interface SignalMetadata_TagsEntry {
  key: string;
  value: string;
}

/** 信号 */
export interface Signal {
  id: string;
  type: SignalType;
  source: SignalSource;
  status: SignalStatus;
  /** 交易参数 */
  symbol: string;
  exchange: string;
  quantity: number;
  price: number;
  stopLoss: number;
  takeProfit: number;
  /** 时间戳 */
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
  executedAt:
    | Date
    | undefined;
  /** 元数据 */
  metadata:
    | SignalMetadata
    | undefined;
  /** 原始数据（JSON字符串） */
  rawData: string;
  /** 错误信息 */
  errorMessage: string;
}

/** 信号列表 */
export interface SignalList {
  signals: Signal[];
  total: number;
  page: number;
  pageSize: number;
}

/** 信号查询请求 */
export interface SignalQueryRequest {
  types: SignalType[];
  sources: SignalSource[];
  statuses: SignalStatus[];
  symbol: string;
  exchange: string;
  startTime: Date | undefined;
  endTime: Date | undefined;
  page: number;
  pageSize: number;
}

/** 信号查询响应 */
export interface SignalQueryResponse {
  signals: SignalList | undefined;
  hasMore: boolean;
}

/** 信号创建请求 */
export interface SignalCreateRequest {
  type: SignalType;
  source: SignalSource;
  symbol: string;
  exchange: string;
  quantity: number;
  price: number;
  stopLoss: number;
  takeProfit: number;
  metadata: SignalMetadata | undefined;
  rawData: string;
}

/** 信号创建响应 */
export interface SignalCreateResponse {
  signal: Signal | undefined;
  success: boolean;
  errorMessage: string;
}

/** 信号更新请求 */
export interface SignalUpdateRequest {
  id: string;
  status: SignalStatus;
  errorMessage: string;
  executedPrice: number;
  executedQuantity: number;
  executedAt: Date | undefined;
}

/** 信号更新响应 */
export interface SignalUpdateResponse {
  signal: Signal | undefined;
  success: boolean;
  errorMessage: string;
}

/** 信号批量处理请求 */
export interface SignalBatchProcessRequest {
  signalIds: string[];
  newStatus: SignalStatus;
  reason: string;
}

/** 信号批量处理响应 */
export interface SignalBatchProcessResponse {
  processedCount: number;
  failedCount: number;
  failedIds: string[];
}

function createBaseSignalMetadata(): SignalMetadata {
  return { strategyId: "", symbol: "", exchange: "", tags: {}, notes: "" };
}

export const SignalMetadata: MessageFns<SignalMetadata> = {
  encode(message: SignalMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.strategyId !== "") {
      writer.uint32(10).string(message.strategyId);
    }
    if (message.symbol !== "") {
      writer.uint32(18).string(message.symbol);
    }
    if (message.exchange !== "") {
      writer.uint32(26).string(message.exchange);
    }
    globalThis.Object.entries(message.tags).forEach(([key, value]: [string, string]) => {
      SignalMetadata_TagsEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    if (message.notes !== "") {
      writer.uint32(42).string(message.notes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.strategyId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.exchange = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = SignalMetadata_TagsEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.tags[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignalMetadata {
    return {
      strategyId: isSet(object.strategyId)
        ? globalThis.String(object.strategyId)
        : isSet(object.strategy_id)
        ? globalThis.String(object.strategy_id)
        : "",
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      exchange: isSet(object.exchange) ? globalThis.String(object.exchange) : "",
      tags: isObject(object.tags)
        ? (globalThis.Object.entries(object.tags) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      notes: isSet(object.notes) ? globalThis.String(object.notes) : "",
    };
  },

  toJSON(message: SignalMetadata): unknown {
    const obj: any = {};
    if (message.strategyId !== "") {
      obj.strategyId = message.strategyId;
    }
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.exchange !== "") {
      obj.exchange = message.exchange;
    }
    if (message.tags) {
      const entries = globalThis.Object.entries(message.tags) as [string, string][];
      if (entries.length > 0) {
        obj.tags = {};
        entries.forEach(([k, v]) => {
          obj.tags[k] = v;
        });
      }
    }
    if (message.notes !== "") {
      obj.notes = message.notes;
    }
    return obj;
  },

  create(base?: DeepPartial<SignalMetadata>): SignalMetadata {
    return SignalMetadata.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignalMetadata>): SignalMetadata {
    const message = createBaseSignalMetadata();
    message.strategyId = object.strategyId ?? "";
    message.symbol = object.symbol ?? "";
    message.exchange = object.exchange ?? "";
    message.tags = (globalThis.Object.entries(object.tags ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.notes = object.notes ?? "";
    return message;
  },
};

function createBaseSignalMetadata_TagsEntry(): SignalMetadata_TagsEntry {
  return { key: "", value: "" };
}

export const SignalMetadata_TagsEntry: MessageFns<SignalMetadata_TagsEntry> = {
  encode(message: SignalMetadata_TagsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalMetadata_TagsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalMetadata_TagsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignalMetadata_TagsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: SignalMetadata_TagsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<SignalMetadata_TagsEntry>): SignalMetadata_TagsEntry {
    return SignalMetadata_TagsEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignalMetadata_TagsEntry>): SignalMetadata_TagsEntry {
    const message = createBaseSignalMetadata_TagsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseSignal(): Signal {
  return {
    id: "",
    type: 0,
    source: 0,
    status: 0,
    symbol: "",
    exchange: "",
    quantity: 0,
    price: 0,
    stopLoss: 0,
    takeProfit: 0,
    createdAt: undefined,
    updatedAt: undefined,
    executedAt: undefined,
    metadata: undefined,
    rawData: "",
    errorMessage: "",
  };
}

export const Signal: MessageFns<Signal> = {
  encode(message: Signal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    if (message.source !== 0) {
      writer.uint32(24).int32(message.source);
    }
    if (message.status !== 0) {
      writer.uint32(32).int32(message.status);
    }
    if (message.symbol !== "") {
      writer.uint32(42).string(message.symbol);
    }
    if (message.exchange !== "") {
      writer.uint32(50).string(message.exchange);
    }
    if (message.quantity !== 0) {
      writer.uint32(57).double(message.quantity);
    }
    if (message.price !== 0) {
      writer.uint32(65).double(message.price);
    }
    if (message.stopLoss !== 0) {
      writer.uint32(73).double(message.stopLoss);
    }
    if (message.takeProfit !== 0) {
      writer.uint32(81).double(message.takeProfit);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(90).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(98).fork()).join();
    }
    if (message.executedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.executedAt), writer.uint32(106).fork()).join();
    }
    if (message.metadata !== undefined) {
      SignalMetadata.encode(message.metadata, writer.uint32(114).fork()).join();
    }
    if (message.rawData !== "") {
      writer.uint32(122).string(message.rawData);
    }
    if (message.errorMessage !== "") {
      writer.uint32(130).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Signal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignal();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.source = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.exchange = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.quantity = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.price = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 73) {
            break;
          }

          message.stopLoss = reader.double();
          continue;
        }
        case 10: {
          if (tag !== 81) {
            break;
          }

          message.takeProfit = reader.double();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.executedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.metadata = SignalMetadata.decode(reader, reader.uint32());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.rawData = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Signal {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      type: isSet(object.type) ? signalTypeFromJSON(object.type) : 0,
      source: isSet(object.source) ? signalSourceFromJSON(object.source) : 0,
      status: isSet(object.status) ? signalStatusFromJSON(object.status) : 0,
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      exchange: isSet(object.exchange) ? globalThis.String(object.exchange) : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
      stopLoss: isSet(object.stopLoss)
        ? globalThis.Number(object.stopLoss)
        : isSet(object.stop_loss)
        ? globalThis.Number(object.stop_loss)
        : 0,
      takeProfit: isSet(object.takeProfit)
        ? globalThis.Number(object.takeProfit)
        : isSet(object.take_profit)
        ? globalThis.Number(object.take_profit)
        : 0,
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
        ? fromJsonTimestamp(object.created_at)
        : undefined,
      updatedAt: isSet(object.updatedAt)
        ? fromJsonTimestamp(object.updatedAt)
        : isSet(object.updated_at)
        ? fromJsonTimestamp(object.updated_at)
        : undefined,
      executedAt: isSet(object.executedAt)
        ? fromJsonTimestamp(object.executedAt)
        : isSet(object.executed_at)
        ? fromJsonTimestamp(object.executed_at)
        : undefined,
      metadata: isSet(object.metadata) ? SignalMetadata.fromJSON(object.metadata) : undefined,
      rawData: isSet(object.rawData)
        ? globalThis.String(object.rawData)
        : isSet(object.raw_data)
        ? globalThis.String(object.raw_data)
        : "",
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: Signal): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.type !== 0) {
      obj.type = signalTypeToJSON(message.type);
    }
    if (message.source !== 0) {
      obj.source = signalSourceToJSON(message.source);
    }
    if (message.status !== 0) {
      obj.status = signalStatusToJSON(message.status);
    }
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.exchange !== "") {
      obj.exchange = message.exchange;
    }
    if (message.quantity !== 0) {
      obj.quantity = message.quantity;
    }
    if (message.price !== 0) {
      obj.price = message.price;
    }
    if (message.stopLoss !== 0) {
      obj.stopLoss = message.stopLoss;
    }
    if (message.takeProfit !== 0) {
      obj.takeProfit = message.takeProfit;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    if (message.executedAt !== undefined) {
      obj.executedAt = message.executedAt.toISOString();
    }
    if (message.metadata !== undefined) {
      obj.metadata = SignalMetadata.toJSON(message.metadata);
    }
    if (message.rawData !== "") {
      obj.rawData = message.rawData;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create(base?: DeepPartial<Signal>): Signal {
    return Signal.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Signal>): Signal {
    const message = createBaseSignal();
    message.id = object.id ?? "";
    message.type = object.type ?? 0;
    message.source = object.source ?? 0;
    message.status = object.status ?? 0;
    message.symbol = object.symbol ?? "";
    message.exchange = object.exchange ?? "";
    message.quantity = object.quantity ?? 0;
    message.price = object.price ?? 0;
    message.stopLoss = object.stopLoss ?? 0;
    message.takeProfit = object.takeProfit ?? 0;
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    message.executedAt = object.executedAt ?? undefined;
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? SignalMetadata.fromPartial(object.metadata)
      : undefined;
    message.rawData = object.rawData ?? "";
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseSignalList(): SignalList {
  return { signals: [], total: 0, page: 0, pageSize: 0 };
}

export const SignalList: MessageFns<SignalList> = {
  encode(message: SignalList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.signals) {
      Signal.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).uint32(message.total);
    }
    if (message.page !== 0) {
      writer.uint32(24).uint32(message.page);
    }
    if (message.pageSize !== 0) {
      writer.uint32(32).uint32(message.pageSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signals.push(Signal.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.page = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.pageSize = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignalList {
    return {
      signals: globalThis.Array.isArray(object?.signals) ? object.signals.map((e: any) => Signal.fromJSON(e)) : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      pageSize: isSet(object.pageSize)
        ? globalThis.Number(object.pageSize)
        : isSet(object.page_size)
        ? globalThis.Number(object.page_size)
        : 0,
    };
  },

  toJSON(message: SignalList): unknown {
    const obj: any = {};
    if (message.signals?.length) {
      obj.signals = message.signals.map((e) => Signal.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    return obj;
  },

  create(base?: DeepPartial<SignalList>): SignalList {
    return SignalList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignalList>): SignalList {
    const message = createBaseSignalList();
    message.signals = object.signals?.map((e) => Signal.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    message.page = object.page ?? 0;
    message.pageSize = object.pageSize ?? 0;
    return message;
  },
};

function createBaseSignalQueryRequest(): SignalQueryRequest {
  return {
    types: [],
    sources: [],
    statuses: [],
    symbol: "",
    exchange: "",
    startTime: undefined,
    endTime: undefined,
    page: 0,
    pageSize: 0,
  };
}

export const SignalQueryRequest: MessageFns<SignalQueryRequest> = {
  encode(message: SignalQueryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.types) {
      writer.int32(v);
    }
    writer.join();
    writer.uint32(18).fork();
    for (const v of message.sources) {
      writer.int32(v);
    }
    writer.join();
    writer.uint32(26).fork();
    for (const v of message.statuses) {
      writer.int32(v);
    }
    writer.join();
    if (message.symbol !== "") {
      writer.uint32(34).string(message.symbol);
    }
    if (message.exchange !== "") {
      writer.uint32(42).string(message.exchange);
    }
    if (message.startTime !== undefined) {
      Timestamp.encode(toTimestamp(message.startTime), writer.uint32(50).fork()).join();
    }
    if (message.endTime !== undefined) {
      Timestamp.encode(toTimestamp(message.endTime), writer.uint32(58).fork()).join();
    }
    if (message.page !== 0) {
      writer.uint32(64).uint32(message.page);
    }
    if (message.pageSize !== 0) {
      writer.uint32(72).uint32(message.pageSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalQueryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalQueryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.types.push(reader.int32() as any);

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.types.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag === 16) {
            message.sources.push(reader.int32() as any);

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.sources.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag === 24) {
            message.statuses.push(reader.int32() as any);

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.statuses.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.exchange = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.startTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.endTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.page = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.pageSize = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignalQueryRequest {
    return {
      types: globalThis.Array.isArray(object?.types) ? object.types.map((e: any) => signalTypeFromJSON(e)) : [],
      sources: globalThis.Array.isArray(object?.sources) ? object.sources.map((e: any) => signalSourceFromJSON(e)) : [],
      statuses: globalThis.Array.isArray(object?.statuses)
        ? object.statuses.map((e: any) => signalStatusFromJSON(e))
        : [],
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      exchange: isSet(object.exchange) ? globalThis.String(object.exchange) : "",
      startTime: isSet(object.startTime)
        ? fromJsonTimestamp(object.startTime)
        : isSet(object.start_time)
        ? fromJsonTimestamp(object.start_time)
        : undefined,
      endTime: isSet(object.endTime)
        ? fromJsonTimestamp(object.endTime)
        : isSet(object.end_time)
        ? fromJsonTimestamp(object.end_time)
        : undefined,
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      pageSize: isSet(object.pageSize)
        ? globalThis.Number(object.pageSize)
        : isSet(object.page_size)
        ? globalThis.Number(object.page_size)
        : 0,
    };
  },

  toJSON(message: SignalQueryRequest): unknown {
    const obj: any = {};
    if (message.types?.length) {
      obj.types = message.types.map((e) => signalTypeToJSON(e));
    }
    if (message.sources?.length) {
      obj.sources = message.sources.map((e) => signalSourceToJSON(e));
    }
    if (message.statuses?.length) {
      obj.statuses = message.statuses.map((e) => signalStatusToJSON(e));
    }
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.exchange !== "") {
      obj.exchange = message.exchange;
    }
    if (message.startTime !== undefined) {
      obj.startTime = message.startTime.toISOString();
    }
    if (message.endTime !== undefined) {
      obj.endTime = message.endTime.toISOString();
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    return obj;
  },

  create(base?: DeepPartial<SignalQueryRequest>): SignalQueryRequest {
    return SignalQueryRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignalQueryRequest>): SignalQueryRequest {
    const message = createBaseSignalQueryRequest();
    message.types = object.types?.map((e) => e) || [];
    message.sources = object.sources?.map((e) => e) || [];
    message.statuses = object.statuses?.map((e) => e) || [];
    message.symbol = object.symbol ?? "";
    message.exchange = object.exchange ?? "";
    message.startTime = object.startTime ?? undefined;
    message.endTime = object.endTime ?? undefined;
    message.page = object.page ?? 0;
    message.pageSize = object.pageSize ?? 0;
    return message;
  },
};

function createBaseSignalQueryResponse(): SignalQueryResponse {
  return { signals: undefined, hasMore: false };
}

export const SignalQueryResponse: MessageFns<SignalQueryResponse> = {
  encode(message: SignalQueryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signals !== undefined) {
      SignalList.encode(message.signals, writer.uint32(10).fork()).join();
    }
    if (message.hasMore !== false) {
      writer.uint32(16).bool(message.hasMore);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalQueryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalQueryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signals = SignalList.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.hasMore = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignalQueryResponse {
    return {
      signals: isSet(object.signals) ? SignalList.fromJSON(object.signals) : undefined,
      hasMore: isSet(object.hasMore)
        ? globalThis.Boolean(object.hasMore)
        : isSet(object.has_more)
        ? globalThis.Boolean(object.has_more)
        : false,
    };
  },

  toJSON(message: SignalQueryResponse): unknown {
    const obj: any = {};
    if (message.signals !== undefined) {
      obj.signals = SignalList.toJSON(message.signals);
    }
    if (message.hasMore !== false) {
      obj.hasMore = message.hasMore;
    }
    return obj;
  },

  create(base?: DeepPartial<SignalQueryResponse>): SignalQueryResponse {
    return SignalQueryResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignalQueryResponse>): SignalQueryResponse {
    const message = createBaseSignalQueryResponse();
    message.signals = (object.signals !== undefined && object.signals !== null)
      ? SignalList.fromPartial(object.signals)
      : undefined;
    message.hasMore = object.hasMore ?? false;
    return message;
  },
};

function createBaseSignalCreateRequest(): SignalCreateRequest {
  return {
    type: 0,
    source: 0,
    symbol: "",
    exchange: "",
    quantity: 0,
    price: 0,
    stopLoss: 0,
    takeProfit: 0,
    metadata: undefined,
    rawData: "",
  };
}

export const SignalCreateRequest: MessageFns<SignalCreateRequest> = {
  encode(message: SignalCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.source !== 0) {
      writer.uint32(16).int32(message.source);
    }
    if (message.symbol !== "") {
      writer.uint32(26).string(message.symbol);
    }
    if (message.exchange !== "") {
      writer.uint32(34).string(message.exchange);
    }
    if (message.quantity !== 0) {
      writer.uint32(41).double(message.quantity);
    }
    if (message.price !== 0) {
      writer.uint32(49).double(message.price);
    }
    if (message.stopLoss !== 0) {
      writer.uint32(57).double(message.stopLoss);
    }
    if (message.takeProfit !== 0) {
      writer.uint32(65).double(message.takeProfit);
    }
    if (message.metadata !== undefined) {
      SignalMetadata.encode(message.metadata, writer.uint32(74).fork()).join();
    }
    if (message.rawData !== "") {
      writer.uint32(82).string(message.rawData);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.source = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.exchange = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.quantity = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.price = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.stopLoss = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.takeProfit = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.metadata = SignalMetadata.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.rawData = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignalCreateRequest {
    return {
      type: isSet(object.type) ? signalTypeFromJSON(object.type) : 0,
      source: isSet(object.source) ? signalSourceFromJSON(object.source) : 0,
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      exchange: isSet(object.exchange) ? globalThis.String(object.exchange) : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
      stopLoss: isSet(object.stopLoss)
        ? globalThis.Number(object.stopLoss)
        : isSet(object.stop_loss)
        ? globalThis.Number(object.stop_loss)
        : 0,
      takeProfit: isSet(object.takeProfit)
        ? globalThis.Number(object.takeProfit)
        : isSet(object.take_profit)
        ? globalThis.Number(object.take_profit)
        : 0,
      metadata: isSet(object.metadata) ? SignalMetadata.fromJSON(object.metadata) : undefined,
      rawData: isSet(object.rawData)
        ? globalThis.String(object.rawData)
        : isSet(object.raw_data)
        ? globalThis.String(object.raw_data)
        : "",
    };
  },

  toJSON(message: SignalCreateRequest): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = signalTypeToJSON(message.type);
    }
    if (message.source !== 0) {
      obj.source = signalSourceToJSON(message.source);
    }
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.exchange !== "") {
      obj.exchange = message.exchange;
    }
    if (message.quantity !== 0) {
      obj.quantity = message.quantity;
    }
    if (message.price !== 0) {
      obj.price = message.price;
    }
    if (message.stopLoss !== 0) {
      obj.stopLoss = message.stopLoss;
    }
    if (message.takeProfit !== 0) {
      obj.takeProfit = message.takeProfit;
    }
    if (message.metadata !== undefined) {
      obj.metadata = SignalMetadata.toJSON(message.metadata);
    }
    if (message.rawData !== "") {
      obj.rawData = message.rawData;
    }
    return obj;
  },

  create(base?: DeepPartial<SignalCreateRequest>): SignalCreateRequest {
    return SignalCreateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignalCreateRequest>): SignalCreateRequest {
    const message = createBaseSignalCreateRequest();
    message.type = object.type ?? 0;
    message.source = object.source ?? 0;
    message.symbol = object.symbol ?? "";
    message.exchange = object.exchange ?? "";
    message.quantity = object.quantity ?? 0;
    message.price = object.price ?? 0;
    message.stopLoss = object.stopLoss ?? 0;
    message.takeProfit = object.takeProfit ?? 0;
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? SignalMetadata.fromPartial(object.metadata)
      : undefined;
    message.rawData = object.rawData ?? "";
    return message;
  },
};

function createBaseSignalCreateResponse(): SignalCreateResponse {
  return { signal: undefined, success: false, errorMessage: "" };
}

export const SignalCreateResponse: MessageFns<SignalCreateResponse> = {
  encode(message: SignalCreateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signal !== undefined) {
      Signal.encode(message.signal, writer.uint32(10).fork()).join();
    }
    if (message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalCreateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalCreateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signal = Signal.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignalCreateResponse {
    return {
      signal: isSet(object.signal) ? Signal.fromJSON(object.signal) : undefined,
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: SignalCreateResponse): unknown {
    const obj: any = {};
    if (message.signal !== undefined) {
      obj.signal = Signal.toJSON(message.signal);
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create(base?: DeepPartial<SignalCreateResponse>): SignalCreateResponse {
    return SignalCreateResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignalCreateResponse>): SignalCreateResponse {
    const message = createBaseSignalCreateResponse();
    message.signal = (object.signal !== undefined && object.signal !== null)
      ? Signal.fromPartial(object.signal)
      : undefined;
    message.success = object.success ?? false;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseSignalUpdateRequest(): SignalUpdateRequest {
  return { id: "", status: 0, errorMessage: "", executedPrice: 0, executedQuantity: 0, executedAt: undefined };
}

export const SignalUpdateRequest: MessageFns<SignalUpdateRequest> = {
  encode(message: SignalUpdateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    if (message.executedPrice !== 0) {
      writer.uint32(33).double(message.executedPrice);
    }
    if (message.executedQuantity !== 0) {
      writer.uint32(41).double(message.executedQuantity);
    }
    if (message.executedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.executedAt), writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalUpdateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalUpdateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.executedPrice = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.executedQuantity = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.executedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignalUpdateRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      status: isSet(object.status) ? signalStatusFromJSON(object.status) : 0,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
      executedPrice: isSet(object.executedPrice)
        ? globalThis.Number(object.executedPrice)
        : isSet(object.executed_price)
        ? globalThis.Number(object.executed_price)
        : 0,
      executedQuantity: isSet(object.executedQuantity)
        ? globalThis.Number(object.executedQuantity)
        : isSet(object.executed_quantity)
        ? globalThis.Number(object.executed_quantity)
        : 0,
      executedAt: isSet(object.executedAt)
        ? fromJsonTimestamp(object.executedAt)
        : isSet(object.executed_at)
        ? fromJsonTimestamp(object.executed_at)
        : undefined,
    };
  },

  toJSON(message: SignalUpdateRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.status !== 0) {
      obj.status = signalStatusToJSON(message.status);
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    if (message.executedPrice !== 0) {
      obj.executedPrice = message.executedPrice;
    }
    if (message.executedQuantity !== 0) {
      obj.executedQuantity = message.executedQuantity;
    }
    if (message.executedAt !== undefined) {
      obj.executedAt = message.executedAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<SignalUpdateRequest>): SignalUpdateRequest {
    return SignalUpdateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignalUpdateRequest>): SignalUpdateRequest {
    const message = createBaseSignalUpdateRequest();
    message.id = object.id ?? "";
    message.status = object.status ?? 0;
    message.errorMessage = object.errorMessage ?? "";
    message.executedPrice = object.executedPrice ?? 0;
    message.executedQuantity = object.executedQuantity ?? 0;
    message.executedAt = object.executedAt ?? undefined;
    return message;
  },
};

function createBaseSignalUpdateResponse(): SignalUpdateResponse {
  return { signal: undefined, success: false, errorMessage: "" };
}

export const SignalUpdateResponse: MessageFns<SignalUpdateResponse> = {
  encode(message: SignalUpdateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signal !== undefined) {
      Signal.encode(message.signal, writer.uint32(10).fork()).join();
    }
    if (message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalUpdateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalUpdateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signal = Signal.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignalUpdateResponse {
    return {
      signal: isSet(object.signal) ? Signal.fromJSON(object.signal) : undefined,
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: SignalUpdateResponse): unknown {
    const obj: any = {};
    if (message.signal !== undefined) {
      obj.signal = Signal.toJSON(message.signal);
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create(base?: DeepPartial<SignalUpdateResponse>): SignalUpdateResponse {
    return SignalUpdateResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignalUpdateResponse>): SignalUpdateResponse {
    const message = createBaseSignalUpdateResponse();
    message.signal = (object.signal !== undefined && object.signal !== null)
      ? Signal.fromPartial(object.signal)
      : undefined;
    message.success = object.success ?? false;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseSignalBatchProcessRequest(): SignalBatchProcessRequest {
  return { signalIds: [], newStatus: 0, reason: "" };
}

export const SignalBatchProcessRequest: MessageFns<SignalBatchProcessRequest> = {
  encode(message: SignalBatchProcessRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.signalIds) {
      writer.uint32(10).string(v!);
    }
    if (message.newStatus !== 0) {
      writer.uint32(16).int32(message.newStatus);
    }
    if (message.reason !== "") {
      writer.uint32(26).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalBatchProcessRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalBatchProcessRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signalIds.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.newStatus = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignalBatchProcessRequest {
    return {
      signalIds: globalThis.Array.isArray(object?.signalIds)
        ? object.signalIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.signal_ids)
        ? object.signal_ids.map((e: any) => globalThis.String(e))
        : [],
      newStatus: isSet(object.newStatus)
        ? signalStatusFromJSON(object.newStatus)
        : isSet(object.new_status)
        ? signalStatusFromJSON(object.new_status)
        : 0,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
    };
  },

  toJSON(message: SignalBatchProcessRequest): unknown {
    const obj: any = {};
    if (message.signalIds?.length) {
      obj.signalIds = message.signalIds;
    }
    if (message.newStatus !== 0) {
      obj.newStatus = signalStatusToJSON(message.newStatus);
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    return obj;
  },

  create(base?: DeepPartial<SignalBatchProcessRequest>): SignalBatchProcessRequest {
    return SignalBatchProcessRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignalBatchProcessRequest>): SignalBatchProcessRequest {
    const message = createBaseSignalBatchProcessRequest();
    message.signalIds = object.signalIds?.map((e) => e) || [];
    message.newStatus = object.newStatus ?? 0;
    message.reason = object.reason ?? "";
    return message;
  },
};

function createBaseSignalBatchProcessResponse(): SignalBatchProcessResponse {
  return { processedCount: 0, failedCount: 0, failedIds: [] };
}

export const SignalBatchProcessResponse: MessageFns<SignalBatchProcessResponse> = {
  encode(message: SignalBatchProcessResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.processedCount !== 0) {
      writer.uint32(8).uint32(message.processedCount);
    }
    if (message.failedCount !== 0) {
      writer.uint32(16).uint32(message.failedCount);
    }
    for (const v of message.failedIds) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalBatchProcessResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalBatchProcessResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.processedCount = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.failedCount = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.failedIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignalBatchProcessResponse {
    return {
      processedCount: isSet(object.processedCount)
        ? globalThis.Number(object.processedCount)
        : isSet(object.processed_count)
        ? globalThis.Number(object.processed_count)
        : 0,
      failedCount: isSet(object.failedCount)
        ? globalThis.Number(object.failedCount)
        : isSet(object.failed_count)
        ? globalThis.Number(object.failed_count)
        : 0,
      failedIds: globalThis.Array.isArray(object?.failedIds)
        ? object.failedIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.failed_ids)
        ? object.failed_ids.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: SignalBatchProcessResponse): unknown {
    const obj: any = {};
    if (message.processedCount !== 0) {
      obj.processedCount = Math.round(message.processedCount);
    }
    if (message.failedCount !== 0) {
      obj.failedCount = Math.round(message.failedCount);
    }
    if (message.failedIds?.length) {
      obj.failedIds = message.failedIds;
    }
    return obj;
  },

  create(base?: DeepPartial<SignalBatchProcessResponse>): SignalBatchProcessResponse {
    return SignalBatchProcessResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignalBatchProcessResponse>): SignalBatchProcessResponse {
    const message = createBaseSignalBatchProcessResponse();
    message.processedCount = object.processedCount ?? 0;
    message.failedCount = object.failedCount ?? 0;
    message.failedIds = object.failedIds?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
