// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               v6.33.4
// source: strategy_subscription.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Empty } from "./google/protobuf/empty.js";
import { Timestamp } from "./google/protobuf/timestamp.js";

export const protobufPackage = "strategy_subscription.v1";

/** 订阅状态枚举 */
export enum SubscriptionStatus {
  SUBSCRIPTION_STATUS_UNSPECIFIED = 0,
  SUBSCRIPTION_STATUS_RUNNING = 1,
  SUBSCRIPTION_STATUS_STOPPED = 2,
  SUBSCRIPTION_STATUS_ERROR = 3,
  UNRECOGNIZED = -1,
}

export function subscriptionStatusFromJSON(object: any): SubscriptionStatus {
  switch (object) {
    case 0:
    case "SUBSCRIPTION_STATUS_UNSPECIFIED":
      return SubscriptionStatus.SUBSCRIPTION_STATUS_UNSPECIFIED;
    case 1:
    case "SUBSCRIPTION_STATUS_RUNNING":
      return SubscriptionStatus.SUBSCRIPTION_STATUS_RUNNING;
    case 2:
    case "SUBSCRIPTION_STATUS_STOPPED":
      return SubscriptionStatus.SUBSCRIPTION_STATUS_STOPPED;
    case 3:
    case "SUBSCRIPTION_STATUS_ERROR":
      return SubscriptionStatus.SUBSCRIPTION_STATUS_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SubscriptionStatus.UNRECOGNIZED;
  }
}

export function subscriptionStatusToJSON(object: SubscriptionStatus): string {
  switch (object) {
    case SubscriptionStatus.SUBSCRIPTION_STATUS_UNSPECIFIED:
      return "SUBSCRIPTION_STATUS_UNSPECIFIED";
    case SubscriptionStatus.SUBSCRIPTION_STATUS_RUNNING:
      return "SUBSCRIPTION_STATUS_RUNNING";
    case SubscriptionStatus.SUBSCRIPTION_STATUS_STOPPED:
      return "SUBSCRIPTION_STATUS_STOPPED";
    case SubscriptionStatus.SUBSCRIPTION_STATUS_ERROR:
      return "SUBSCRIPTION_STATUS_ERROR";
    case SubscriptionStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 订阅请求 */
export interface SubscribeRequest {
  /** 用户ID */
  userId: string;
  /** 订阅ID（strategy_order.id，多 symbol 时为 "orderId:symbol"） */
  subscriptionId: string;
  /** 策略ID */
  strategyId: string;
  /** 策略名称 */
  strategyName: string;
  /** 策略代码（hquant DSL） */
  code: string;
  /** 交易对（如 BTC-USDT） */
  symbol: string;
  /** 交易所（binance, okx） */
  exchange: string;
  /** 交易类型（spot, futures, delivery） */
  tradeType: string;
  /** K线周期（15m, 1h, 1d） */
  period: string;
  /** 策略参数（JSON 字符串） */
  parameters: string;
  /** 风控配置（JSON 字符串） */
  riskConfig: string;
  /** 是否实盘 */
  live: boolean;
}

/** 订阅响应 */
export interface SubscriptionResponse {
  /** 订阅ID */
  subscriptionId: string;
  /** 用户ID */
  userId: string;
  /** 实例Key（用于取消订阅） */
  instanceKey: string;
  /** 订阅状态 */
  status: SubscriptionStatus;
  /** 实例引用计数 */
  refCount: number;
  /** NATS 主题 */
  natsSubject: string;
  startedAt: Date | undefined;
  stoppedAt: Date | undefined;
}

/** 取消订阅请求 */
export interface UnsubscribeRequest {
  /** 订阅ID */
  subscriptionId: string;
  /** 实例Key */
  instanceKey: string;
}

/** 获取订阅请求 */
export interface GetSubscriptionRequest {
  /** 订阅ID */
  subscriptionId: string;
}

/** 列出订阅请求 */
export interface ListSubscriptionsRequest {
  /** 用户ID（可选，为空则返回所有） */
  userId: string;
  /** 分页大小 */
  pageSize: number;
  /** 分页令牌 */
  pageToken: string;
}

/** 列出订阅响应 */
export interface ListSubscriptionsResponse {
  subscriptions: SubscriptionResponse[];
  nextPageToken: string;
  totalCount: number;
}

/** 实例统计响应 */
export interface InstanceStatsResponse {
  /** 总实例数 */
  totalInstances: number;
  /** 运行中实例数 */
  runningInstances: number;
  /** 已停止实例数 */
  stoppedInstances: number;
  /** 错误实例数 */
  errorInstances: number;
  /** 总订阅数 */
  totalSubscriptions: number;
  /** 按交易所分组 */
  instancesByExchange: { [key: string]: number };
  /** 按策略分组 */
  instancesByStrategy: { [key: string]: number };
}

export interface InstanceStatsResponse_InstancesByExchangeEntry {
  key: string;
  value: number;
}

export interface InstanceStatsResponse_InstancesByStrategyEntry {
  key: string;
  value: number;
}

function createBaseSubscribeRequest(): SubscribeRequest {
  return {
    userId: "",
    subscriptionId: "",
    strategyId: "",
    strategyName: "",
    code: "",
    symbol: "",
    exchange: "",
    tradeType: "",
    period: "",
    parameters: "",
    riskConfig: "",
    live: false,
  };
}

export const SubscribeRequest: MessageFns<SubscribeRequest> = {
  encode(message: SubscribeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.subscriptionId !== "") {
      writer.uint32(18).string(message.subscriptionId);
    }
    if (message.strategyId !== "") {
      writer.uint32(26).string(message.strategyId);
    }
    if (message.strategyName !== "") {
      writer.uint32(34).string(message.strategyName);
    }
    if (message.code !== "") {
      writer.uint32(42).string(message.code);
    }
    if (message.symbol !== "") {
      writer.uint32(50).string(message.symbol);
    }
    if (message.exchange !== "") {
      writer.uint32(58).string(message.exchange);
    }
    if (message.tradeType !== "") {
      writer.uint32(66).string(message.tradeType);
    }
    if (message.period !== "") {
      writer.uint32(74).string(message.period);
    }
    if (message.parameters !== "") {
      writer.uint32(82).string(message.parameters);
    }
    if (message.riskConfig !== "") {
      writer.uint32(90).string(message.riskConfig);
    }
    if (message.live !== false) {
      writer.uint32(96).bool(message.live);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subscriptionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.strategyId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.strategyName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.exchange = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.tradeType = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.period = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.parameters = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.riskConfig = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.live = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubscribeRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      subscriptionId: isSet(object.subscriptionId)
        ? globalThis.String(object.subscriptionId)
        : isSet(object.subscription_id)
        ? globalThis.String(object.subscription_id)
        : "",
      strategyId: isSet(object.strategyId)
        ? globalThis.String(object.strategyId)
        : isSet(object.strategy_id)
        ? globalThis.String(object.strategy_id)
        : "",
      strategyName: isSet(object.strategyName)
        ? globalThis.String(object.strategyName)
        : isSet(object.strategy_name)
        ? globalThis.String(object.strategy_name)
        : "",
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      exchange: isSet(object.exchange) ? globalThis.String(object.exchange) : "",
      tradeType: isSet(object.tradeType)
        ? globalThis.String(object.tradeType)
        : isSet(object.trade_type)
        ? globalThis.String(object.trade_type)
        : "",
      period: isSet(object.period) ? globalThis.String(object.period) : "",
      parameters: isSet(object.parameters) ? globalThis.String(object.parameters) : "",
      riskConfig: isSet(object.riskConfig)
        ? globalThis.String(object.riskConfig)
        : isSet(object.risk_config)
        ? globalThis.String(object.risk_config)
        : "",
      live: isSet(object.live) ? globalThis.Boolean(object.live) : false,
    };
  },

  toJSON(message: SubscribeRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.subscriptionId !== "") {
      obj.subscriptionId = message.subscriptionId;
    }
    if (message.strategyId !== "") {
      obj.strategyId = message.strategyId;
    }
    if (message.strategyName !== "") {
      obj.strategyName = message.strategyName;
    }
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.exchange !== "") {
      obj.exchange = message.exchange;
    }
    if (message.tradeType !== "") {
      obj.tradeType = message.tradeType;
    }
    if (message.period !== "") {
      obj.period = message.period;
    }
    if (message.parameters !== "") {
      obj.parameters = message.parameters;
    }
    if (message.riskConfig !== "") {
      obj.riskConfig = message.riskConfig;
    }
    if (message.live !== false) {
      obj.live = message.live;
    }
    return obj;
  },

  create(base?: DeepPartial<SubscribeRequest>): SubscribeRequest {
    return SubscribeRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SubscribeRequest>): SubscribeRequest {
    const message = createBaseSubscribeRequest();
    message.userId = object.userId ?? "";
    message.subscriptionId = object.subscriptionId ?? "";
    message.strategyId = object.strategyId ?? "";
    message.strategyName = object.strategyName ?? "";
    message.code = object.code ?? "";
    message.symbol = object.symbol ?? "";
    message.exchange = object.exchange ?? "";
    message.tradeType = object.tradeType ?? "";
    message.period = object.period ?? "";
    message.parameters = object.parameters ?? "";
    message.riskConfig = object.riskConfig ?? "";
    message.live = object.live ?? false;
    return message;
  },
};

function createBaseSubscriptionResponse(): SubscriptionResponse {
  return {
    subscriptionId: "",
    userId: "",
    instanceKey: "",
    status: 0,
    refCount: 0,
    natsSubject: "",
    startedAt: undefined,
    stoppedAt: undefined,
  };
}

export const SubscriptionResponse: MessageFns<SubscriptionResponse> = {
  encode(message: SubscriptionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subscriptionId !== "") {
      writer.uint32(10).string(message.subscriptionId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.instanceKey !== "") {
      writer.uint32(26).string(message.instanceKey);
    }
    if (message.status !== 0) {
      writer.uint32(32).int32(message.status);
    }
    if (message.refCount !== 0) {
      writer.uint32(40).int32(message.refCount);
    }
    if (message.natsSubject !== "") {
      writer.uint32(50).string(message.natsSubject);
    }
    if (message.startedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.startedAt), writer.uint32(58).fork()).join();
    }
    if (message.stoppedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.stoppedAt), writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscriptionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscriptionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subscriptionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.instanceKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.refCount = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.natsSubject = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.startedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.stoppedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubscriptionResponse {
    return {
      subscriptionId: isSet(object.subscriptionId)
        ? globalThis.String(object.subscriptionId)
        : isSet(object.subscription_id)
        ? globalThis.String(object.subscription_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      instanceKey: isSet(object.instanceKey)
        ? globalThis.String(object.instanceKey)
        : isSet(object.instance_key)
        ? globalThis.String(object.instance_key)
        : "",
      status: isSet(object.status) ? subscriptionStatusFromJSON(object.status) : 0,
      refCount: isSet(object.refCount)
        ? globalThis.Number(object.refCount)
        : isSet(object.ref_count)
        ? globalThis.Number(object.ref_count)
        : 0,
      natsSubject: isSet(object.natsSubject)
        ? globalThis.String(object.natsSubject)
        : isSet(object.nats_subject)
        ? globalThis.String(object.nats_subject)
        : "",
      startedAt: isSet(object.startedAt)
        ? fromJsonTimestamp(object.startedAt)
        : isSet(object.started_at)
        ? fromJsonTimestamp(object.started_at)
        : undefined,
      stoppedAt: isSet(object.stoppedAt)
        ? fromJsonTimestamp(object.stoppedAt)
        : isSet(object.stopped_at)
        ? fromJsonTimestamp(object.stopped_at)
        : undefined,
    };
  },

  toJSON(message: SubscriptionResponse): unknown {
    const obj: any = {};
    if (message.subscriptionId !== "") {
      obj.subscriptionId = message.subscriptionId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.instanceKey !== "") {
      obj.instanceKey = message.instanceKey;
    }
    if (message.status !== 0) {
      obj.status = subscriptionStatusToJSON(message.status);
    }
    if (message.refCount !== 0) {
      obj.refCount = Math.round(message.refCount);
    }
    if (message.natsSubject !== "") {
      obj.natsSubject = message.natsSubject;
    }
    if (message.startedAt !== undefined) {
      obj.startedAt = message.startedAt.toISOString();
    }
    if (message.stoppedAt !== undefined) {
      obj.stoppedAt = message.stoppedAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<SubscriptionResponse>): SubscriptionResponse {
    return SubscriptionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SubscriptionResponse>): SubscriptionResponse {
    const message = createBaseSubscriptionResponse();
    message.subscriptionId = object.subscriptionId ?? "";
    message.userId = object.userId ?? "";
    message.instanceKey = object.instanceKey ?? "";
    message.status = object.status ?? 0;
    message.refCount = object.refCount ?? 0;
    message.natsSubject = object.natsSubject ?? "";
    message.startedAt = object.startedAt ?? undefined;
    message.stoppedAt = object.stoppedAt ?? undefined;
    return message;
  },
};

function createBaseUnsubscribeRequest(): UnsubscribeRequest {
  return { subscriptionId: "", instanceKey: "" };
}

export const UnsubscribeRequest: MessageFns<UnsubscribeRequest> = {
  encode(message: UnsubscribeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subscriptionId !== "") {
      writer.uint32(10).string(message.subscriptionId);
    }
    if (message.instanceKey !== "") {
      writer.uint32(18).string(message.instanceKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UnsubscribeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnsubscribeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subscriptionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.instanceKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UnsubscribeRequest {
    return {
      subscriptionId: isSet(object.subscriptionId)
        ? globalThis.String(object.subscriptionId)
        : isSet(object.subscription_id)
        ? globalThis.String(object.subscription_id)
        : "",
      instanceKey: isSet(object.instanceKey)
        ? globalThis.String(object.instanceKey)
        : isSet(object.instance_key)
        ? globalThis.String(object.instance_key)
        : "",
    };
  },

  toJSON(message: UnsubscribeRequest): unknown {
    const obj: any = {};
    if (message.subscriptionId !== "") {
      obj.subscriptionId = message.subscriptionId;
    }
    if (message.instanceKey !== "") {
      obj.instanceKey = message.instanceKey;
    }
    return obj;
  },

  create(base?: DeepPartial<UnsubscribeRequest>): UnsubscribeRequest {
    return UnsubscribeRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UnsubscribeRequest>): UnsubscribeRequest {
    const message = createBaseUnsubscribeRequest();
    message.subscriptionId = object.subscriptionId ?? "";
    message.instanceKey = object.instanceKey ?? "";
    return message;
  },
};

function createBaseGetSubscriptionRequest(): GetSubscriptionRequest {
  return { subscriptionId: "" };
}

export const GetSubscriptionRequest: MessageFns<GetSubscriptionRequest> = {
  encode(message: GetSubscriptionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subscriptionId !== "") {
      writer.uint32(10).string(message.subscriptionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSubscriptionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSubscriptionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subscriptionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSubscriptionRequest {
    return {
      subscriptionId: isSet(object.subscriptionId)
        ? globalThis.String(object.subscriptionId)
        : isSet(object.subscription_id)
        ? globalThis.String(object.subscription_id)
        : "",
    };
  },

  toJSON(message: GetSubscriptionRequest): unknown {
    const obj: any = {};
    if (message.subscriptionId !== "") {
      obj.subscriptionId = message.subscriptionId;
    }
    return obj;
  },

  create(base?: DeepPartial<GetSubscriptionRequest>): GetSubscriptionRequest {
    return GetSubscriptionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetSubscriptionRequest>): GetSubscriptionRequest {
    const message = createBaseGetSubscriptionRequest();
    message.subscriptionId = object.subscriptionId ?? "";
    return message;
  },
};

function createBaseListSubscriptionsRequest(): ListSubscriptionsRequest {
  return { userId: "", pageSize: 0, pageToken: "" };
}

export const ListSubscriptionsRequest: MessageFns<ListSubscriptionsRequest> = {
  encode(message: ListSubscriptionsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.pageSize !== 0) {
      writer.uint32(16).int32(message.pageSize);
    }
    if (message.pageToken !== "") {
      writer.uint32(26).string(message.pageToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListSubscriptionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListSubscriptionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pageToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListSubscriptionsRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      pageSize: isSet(object.pageSize)
        ? globalThis.Number(object.pageSize)
        : isSet(object.page_size)
        ? globalThis.Number(object.page_size)
        : 0,
      pageToken: isSet(object.pageToken)
        ? globalThis.String(object.pageToken)
        : isSet(object.page_token)
        ? globalThis.String(object.page_token)
        : "",
    };
  },

  toJSON(message: ListSubscriptionsRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    if (message.pageToken !== "") {
      obj.pageToken = message.pageToken;
    }
    return obj;
  },

  create(base?: DeepPartial<ListSubscriptionsRequest>): ListSubscriptionsRequest {
    return ListSubscriptionsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListSubscriptionsRequest>): ListSubscriptionsRequest {
    const message = createBaseListSubscriptionsRequest();
    message.userId = object.userId ?? "";
    message.pageSize = object.pageSize ?? 0;
    message.pageToken = object.pageToken ?? "";
    return message;
  },
};

function createBaseListSubscriptionsResponse(): ListSubscriptionsResponse {
  return { subscriptions: [], nextPageToken: "", totalCount: 0 };
}

export const ListSubscriptionsResponse: MessageFns<ListSubscriptionsResponse> = {
  encode(message: ListSubscriptionsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.subscriptions) {
      SubscriptionResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.nextPageToken !== "") {
      writer.uint32(18).string(message.nextPageToken);
    }
    if (message.totalCount !== 0) {
      writer.uint32(24).int32(message.totalCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListSubscriptionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListSubscriptionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subscriptions.push(SubscriptionResponse.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nextPageToken = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListSubscriptionsResponse {
    return {
      subscriptions: globalThis.Array.isArray(object?.subscriptions)
        ? object.subscriptions.map((e: any) => SubscriptionResponse.fromJSON(e))
        : [],
      nextPageToken: isSet(object.nextPageToken)
        ? globalThis.String(object.nextPageToken)
        : isSet(object.next_page_token)
        ? globalThis.String(object.next_page_token)
        : "",
      totalCount: isSet(object.totalCount)
        ? globalThis.Number(object.totalCount)
        : isSet(object.total_count)
        ? globalThis.Number(object.total_count)
        : 0,
    };
  },

  toJSON(message: ListSubscriptionsResponse): unknown {
    const obj: any = {};
    if (message.subscriptions?.length) {
      obj.subscriptions = message.subscriptions.map((e) => SubscriptionResponse.toJSON(e));
    }
    if (message.nextPageToken !== "") {
      obj.nextPageToken = message.nextPageToken;
    }
    if (message.totalCount !== 0) {
      obj.totalCount = Math.round(message.totalCount);
    }
    return obj;
  },

  create(base?: DeepPartial<ListSubscriptionsResponse>): ListSubscriptionsResponse {
    return ListSubscriptionsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListSubscriptionsResponse>): ListSubscriptionsResponse {
    const message = createBaseListSubscriptionsResponse();
    message.subscriptions = object.subscriptions?.map((e) => SubscriptionResponse.fromPartial(e)) || [];
    message.nextPageToken = object.nextPageToken ?? "";
    message.totalCount = object.totalCount ?? 0;
    return message;
  },
};

function createBaseInstanceStatsResponse(): InstanceStatsResponse {
  return {
    totalInstances: 0,
    runningInstances: 0,
    stoppedInstances: 0,
    errorInstances: 0,
    totalSubscriptions: 0,
    instancesByExchange: {},
    instancesByStrategy: {},
  };
}

export const InstanceStatsResponse: MessageFns<InstanceStatsResponse> = {
  encode(message: InstanceStatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalInstances !== 0) {
      writer.uint32(8).int32(message.totalInstances);
    }
    if (message.runningInstances !== 0) {
      writer.uint32(16).int32(message.runningInstances);
    }
    if (message.stoppedInstances !== 0) {
      writer.uint32(24).int32(message.stoppedInstances);
    }
    if (message.errorInstances !== 0) {
      writer.uint32(32).int32(message.errorInstances);
    }
    if (message.totalSubscriptions !== 0) {
      writer.uint32(40).int32(message.totalSubscriptions);
    }
    globalThis.Object.entries(message.instancesByExchange).forEach(([key, value]: [string, number]) => {
      InstanceStatsResponse_InstancesByExchangeEntry.encode({ key: key as any, value }, writer.uint32(50).fork())
        .join();
    });
    globalThis.Object.entries(message.instancesByStrategy).forEach(([key, value]: [string, number]) => {
      InstanceStatsResponse_InstancesByStrategyEntry.encode({ key: key as any, value }, writer.uint32(58).fork())
        .join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InstanceStatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInstanceStatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.totalInstances = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.runningInstances = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.stoppedInstances = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.errorInstances = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.totalSubscriptions = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = InstanceStatsResponse_InstancesByExchangeEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.instancesByExchange[entry6.key] = entry6.value;
          }
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          const entry7 = InstanceStatsResponse_InstancesByStrategyEntry.decode(reader, reader.uint32());
          if (entry7.value !== undefined) {
            message.instancesByStrategy[entry7.key] = entry7.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InstanceStatsResponse {
    return {
      totalInstances: isSet(object.totalInstances)
        ? globalThis.Number(object.totalInstances)
        : isSet(object.total_instances)
        ? globalThis.Number(object.total_instances)
        : 0,
      runningInstances: isSet(object.runningInstances)
        ? globalThis.Number(object.runningInstances)
        : isSet(object.running_instances)
        ? globalThis.Number(object.running_instances)
        : 0,
      stoppedInstances: isSet(object.stoppedInstances)
        ? globalThis.Number(object.stoppedInstances)
        : isSet(object.stopped_instances)
        ? globalThis.Number(object.stopped_instances)
        : 0,
      errorInstances: isSet(object.errorInstances)
        ? globalThis.Number(object.errorInstances)
        : isSet(object.error_instances)
        ? globalThis.Number(object.error_instances)
        : 0,
      totalSubscriptions: isSet(object.totalSubscriptions)
        ? globalThis.Number(object.totalSubscriptions)
        : isSet(object.total_subscriptions)
        ? globalThis.Number(object.total_subscriptions)
        : 0,
      instancesByExchange: isObject(object.instancesByExchange)
        ? (globalThis.Object.entries(object.instancesByExchange) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : isObject(object.instances_by_exchange)
        ? (globalThis.Object.entries(object.instances_by_exchange) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
      instancesByStrategy: isObject(object.instancesByStrategy)
        ? (globalThis.Object.entries(object.instancesByStrategy) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : isObject(object.instances_by_strategy)
        ? (globalThis.Object.entries(object.instances_by_strategy) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: InstanceStatsResponse): unknown {
    const obj: any = {};
    if (message.totalInstances !== 0) {
      obj.totalInstances = Math.round(message.totalInstances);
    }
    if (message.runningInstances !== 0) {
      obj.runningInstances = Math.round(message.runningInstances);
    }
    if (message.stoppedInstances !== 0) {
      obj.stoppedInstances = Math.round(message.stoppedInstances);
    }
    if (message.errorInstances !== 0) {
      obj.errorInstances = Math.round(message.errorInstances);
    }
    if (message.totalSubscriptions !== 0) {
      obj.totalSubscriptions = Math.round(message.totalSubscriptions);
    }
    if (message.instancesByExchange) {
      const entries = globalThis.Object.entries(message.instancesByExchange) as [string, number][];
      if (entries.length > 0) {
        obj.instancesByExchange = {};
        entries.forEach(([k, v]) => {
          obj.instancesByExchange[k] = Math.round(v);
        });
      }
    }
    if (message.instancesByStrategy) {
      const entries = globalThis.Object.entries(message.instancesByStrategy) as [string, number][];
      if (entries.length > 0) {
        obj.instancesByStrategy = {};
        entries.forEach(([k, v]) => {
          obj.instancesByStrategy[k] = Math.round(v);
        });
      }
    }
    return obj;
  },

  create(base?: DeepPartial<InstanceStatsResponse>): InstanceStatsResponse {
    return InstanceStatsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<InstanceStatsResponse>): InstanceStatsResponse {
    const message = createBaseInstanceStatsResponse();
    message.totalInstances = object.totalInstances ?? 0;
    message.runningInstances = object.runningInstances ?? 0;
    message.stoppedInstances = object.stoppedInstances ?? 0;
    message.errorInstances = object.errorInstances ?? 0;
    message.totalSubscriptions = object.totalSubscriptions ?? 0;
    message.instancesByExchange = (globalThis.Object.entries(object.instancesByExchange ?? {}) as [string, number][])
      .reduce((acc: { [key: string]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Number(value);
        }
        return acc;
      }, {});
    message.instancesByStrategy = (globalThis.Object.entries(object.instancesByStrategy ?? {}) as [string, number][])
      .reduce((acc: { [key: string]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Number(value);
        }
        return acc;
      }, {});
    return message;
  },
};

function createBaseInstanceStatsResponse_InstancesByExchangeEntry(): InstanceStatsResponse_InstancesByExchangeEntry {
  return { key: "", value: 0 };
}

export const InstanceStatsResponse_InstancesByExchangeEntry: MessageFns<
  InstanceStatsResponse_InstancesByExchangeEntry
> = {
  encode(
    message: InstanceStatsResponse_InstancesByExchangeEntry,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).int32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InstanceStatsResponse_InstancesByExchangeEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInstanceStatsResponse_InstancesByExchangeEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InstanceStatsResponse_InstancesByExchangeEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: InstanceStatsResponse_InstancesByExchangeEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create(
    base?: DeepPartial<InstanceStatsResponse_InstancesByExchangeEntry>,
  ): InstanceStatsResponse_InstancesByExchangeEntry {
    return InstanceStatsResponse_InstancesByExchangeEntry.fromPartial(base ?? {});
  },
  fromPartial(
    object: DeepPartial<InstanceStatsResponse_InstancesByExchangeEntry>,
  ): InstanceStatsResponse_InstancesByExchangeEntry {
    const message = createBaseInstanceStatsResponse_InstancesByExchangeEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseInstanceStatsResponse_InstancesByStrategyEntry(): InstanceStatsResponse_InstancesByStrategyEntry {
  return { key: "", value: 0 };
}

export const InstanceStatsResponse_InstancesByStrategyEntry: MessageFns<
  InstanceStatsResponse_InstancesByStrategyEntry
> = {
  encode(
    message: InstanceStatsResponse_InstancesByStrategyEntry,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).int32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InstanceStatsResponse_InstancesByStrategyEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInstanceStatsResponse_InstancesByStrategyEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InstanceStatsResponse_InstancesByStrategyEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: InstanceStatsResponse_InstancesByStrategyEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create(
    base?: DeepPartial<InstanceStatsResponse_InstancesByStrategyEntry>,
  ): InstanceStatsResponse_InstancesByStrategyEntry {
    return InstanceStatsResponse_InstancesByStrategyEntry.fromPartial(base ?? {});
  },
  fromPartial(
    object: DeepPartial<InstanceStatsResponse_InstancesByStrategyEntry>,
  ): InstanceStatsResponse_InstancesByStrategyEntry {
    const message = createBaseInstanceStatsResponse_InstancesByStrategyEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

/** 策略订阅服务 */
export type SubscriptionServiceDefinition = typeof SubscriptionServiceDefinition;
export const SubscriptionServiceDefinition = {
  name: "SubscriptionService",
  fullName: "strategy_subscription.v1.SubscriptionService",
  methods: {
    /** 订阅策略（启动实时运行） */
    subscribe: {
      name: "Subscribe",
      requestType: SubscribeRequest,
      requestStream: false,
      responseType: SubscriptionResponse,
      responseStream: false,
      options: {},
    },
    /** 取消订阅 */
    unsubscribe: {
      name: "Unsubscribe",
      requestType: UnsubscribeRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** 获取订阅状态 */
    getSubscription: {
      name: "GetSubscription",
      requestType: GetSubscriptionRequest,
      requestStream: false,
      responseType: SubscriptionResponse,
      responseStream: false,
      options: {},
    },
    /** 列出用户订阅 */
    listSubscriptions: {
      name: "ListSubscriptions",
      requestType: ListSubscriptionsRequest,
      requestStream: false,
      responseType: ListSubscriptionsResponse,
      responseStream: false,
      options: {},
    },
    /** 获取实例统计信息（用于监控） */
    getInstanceStats: {
      name: "GetInstanceStats",
      requestType: Empty,
      requestStream: false,
      responseType: InstanceStatsResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface SubscriptionServiceImplementation<CallContextExt = {}> {
  /** 订阅策略（启动实时运行） */
  subscribe(
    request: SubscribeRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SubscriptionResponse>>;
  /** 取消订阅 */
  unsubscribe(request: UnsubscribeRequest, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  /** 获取订阅状态 */
  getSubscription(
    request: GetSubscriptionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SubscriptionResponse>>;
  /** 列出用户订阅 */
  listSubscriptions(
    request: ListSubscriptionsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ListSubscriptionsResponse>>;
  /** 获取实例统计信息（用于监控） */
  getInstanceStats(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<InstanceStatsResponse>>;
}

export interface SubscriptionServiceClient<CallOptionsExt = {}> {
  /** 订阅策略（启动实时运行） */
  subscribe(
    request: DeepPartial<SubscribeRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SubscriptionResponse>;
  /** 取消订阅 */
  unsubscribe(request: DeepPartial<UnsubscribeRequest>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  /** 获取订阅状态 */
  getSubscription(
    request: DeepPartial<GetSubscriptionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SubscriptionResponse>;
  /** 列出用户订阅 */
  listSubscriptions(
    request: DeepPartial<ListSubscriptionsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ListSubscriptionsResponse>;
  /** 获取实例统计信息（用于监控） */
  getInstanceStats(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<InstanceStatsResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
