// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type NormalizedCandle struct {
	ID           int64            `db:"id" json:"id"`
	Symbol       string           `db:"symbol" json:"symbol"`
	Exchange     string           `db:"exchange" json:"exchange"`
	TradeType    string           `db:"trade_type" json:"trade_type"`
	Period       string           `db:"period" json:"period"`
	Timestamp    int64            `db:"timestamp" json:"timestamp"`
	Open         decimal.Decimal  `db:"open" json:"open"`
	High         decimal.Decimal  `db:"high" json:"high"`
	Low          decimal.Decimal  `db:"low" json:"low"`
	Close        decimal.Decimal  `db:"close" json:"close"`
	Volume       decimal.Decimal  `db:"volume" json:"volume"`
	BuyVolume    decimal.Decimal  `db:"buy_volume" json:"buy_volume"`
	SymbolFamily pgtype.Text      `db:"symbol_family" json:"symbol_family"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type PartitionRegistry struct {
	ID        int64            `db:"id" json:"id"`
	TableName string           `db:"table_name" json:"table_name"`
	Year      int32            `db:"year" json:"year"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type SymbolInfo struct {
	ID                int64            `db:"id" json:"id"`
	Exchange          string           `db:"exchange" json:"exchange"`
	Symbol            string           `db:"symbol" json:"symbol"`
	RawSymbol         string           `db:"raw_symbol" json:"raw_symbol"`
	BaseCurrency      string           `db:"base_currency" json:"base_currency"`
	QuoteCurrency     string           `db:"quote_currency" json:"quote_currency"`
	TradeType         string           `db:"trade_type" json:"trade_type"`
	TickSize          pgtype.Text      `db:"tick_size" json:"tick_size"`
	StepSize          pgtype.Text      `db:"step_size" json:"step_size"`
	MinQty            pgtype.Text      `db:"min_qty" json:"min_qty"`
	MaxQty            pgtype.Text      `db:"max_qty" json:"max_qty"`
	QuantityPrecision pgtype.Int4      `db:"quantity_precision" json:"quantity_precision"`
	PricePrecision    pgtype.Int4      `db:"price_precision" json:"price_precision"`
	Status            pgtype.Text      `db:"status" json:"status"`
	ContractValue     pgtype.Numeric   `db:"contract_value" json:"contract_value"`
	MaxLeverage       pgtype.Numeric   `db:"max_leverage" json:"max_leverage"`
	SyncEnabled       pgtype.Bool      `db:"sync_enabled" json:"sync_enabled"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type SymbolSyncStatus struct {
	ID             int64            `db:"id" json:"id"`
	Exchange       string           `db:"exchange" json:"exchange"`
	Symbol         string           `db:"symbol" json:"symbol"`
	TradeType      string           `db:"trade_type" json:"trade_type"`
	EarliestDataTs pgtype.Int8      `db:"earliest_data_ts" json:"earliest_data_ts"`
	LatestSyncTs   pgtype.Int8      `db:"latest_sync_ts" json:"latest_sync_ts"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
