import type { DeepPartial, Styles } from 'klinecharts'

export const lightTheme: DeepPartial<Styles> = {
  grid: {
    show: true,
    horizontal: {
      show: true,
      size: 1,
      color: '#EDEDED',
    },
    vertical: {
      show: true,
      size: 1,
      color: '#EDEDED',
    },
  },
  candle: {
    bar: {
      upColor: '#26A69A',
      downColor: '#EF5350',
      noChangeColor: '#666666',
      upBorderColor: '#26A69A',
      downBorderColor: '#EF5350',
      noChangeBorderColor: '#666666',
      upWickColor: '#26A69A',
      downWickColor: '#EF5350',
      noChangeWickColor: '#666666',
    },
    priceMark: {
      show: true,
      high: {
        show: true,
        color: '#76808F',
        textOffset: 5,
        textSize: 10,
        textFamily: 'Helvetica Neue',
        textWeight: 'normal',
      },
      low: {
        show: true,
        color: '#76808F',
        textOffset: 5,
        textSize: 10,
        textFamily: 'Helvetica Neue',
        textWeight: 'normal',
      },
      last: {
        show: true,
        upColor: '#26A69A',
        downColor: '#EF5350',
        noChangeColor: '#666666',
        line: {
          show: true,
          size: 1,
        },
        text: {
          show: true,
          size: 12,
          paddingLeft: 4,
          paddingTop: 4,
          paddingRight: 4,
          paddingBottom: 4,
          color: '#FFFFFF',
          family: 'Helvetica Neue',
          weight: 'normal',
          borderRadius: 2,
        },
      },
    },
    tooltip: {
      rect: {
        paddingLeft: 4,
        paddingRight: 4,
        paddingTop: 4,
        paddingBottom: 4,
        offsetLeft: 4,
        offsetTop: 4,
        offsetRight: 4,
        offsetBottom: 4,
        borderRadius: 4,
        borderSize: 1,
        borderColor: '#F2F3F5',
        color: '#FEFEFE',
      },
      legend: {
        defaultValue: 'n/a',
        size: 12,
        family: 'Helvetica Neue',
        weight: 'normal',
        color: '#76808F',
        marginLeft: 8,
        marginTop: 4,
        marginRight: 8,
        marginBottom: 4,
      },
    },
  },
  indicator: {
    ohlc: {
      upColor: '#26A69A',
      downColor: '#EF5350',
      noChangeColor: '#666666',
    },
    lines: [
      { size: 1, color: '#FF9600' },
      { size: 1, color: '#935EBD' },
      { size: 1, color: '#2196F3' },
      { size: 1, color: '#E11D74' },
      { size: 1, color: '#01C5C4' },
    ],
    tooltip: {
      title: {
        showName: true,
        showParams: true,
      },
      legend: {
        defaultValue: 'n/a',
        size: 12,
        family: 'Helvetica Neue',
        weight: 'normal',
        color: '#76808F',
        marginLeft: 8,
        marginTop: 4,
        marginRight: 8,
        marginBottom: 4,
      },
    },
  },
  xAxis: {
    show: true,
    axisLine: {
      show: true,
      color: '#DDDDDD',
      size: 1,
    },
    tickText: {
      show: true,
      color: '#76808F',
      family: 'Helvetica Neue',
      weight: 'normal',
      size: 12,
      marginStart: 4,
      marginEnd: 4,
    },
    tickLine: {
      show: true,
      size: 1,
      length: 3,
      color: '#DDDDDD',
    },
  },
  yAxis: {
    show: true,
    axisLine: {
      show: true,
      color: '#DDDDDD',
      size: 1,
    },
    tickText: {
      show: true,
      color: '#76808F',
      family: 'Helvetica Neue',
      weight: 'normal',
      size: 12,
      marginStart: 4,
      marginEnd: 4,
    },
    tickLine: {
      show: true,
      size: 1,
      length: 3,
      color: '#DDDDDD',
    },
  },
  separator: {
    size: 1,
    color: '#DDDDDD',
    fill: true,
    activeBackgroundColor: 'rgba(33, 150, 243, 0.08)',
  },
  crosshair: {
    show: true,
    horizontal: {
      show: true,
      line: {
        show: true,
        size: 1,
        color: '#76808F',
      },
      text: {
        show: true,
        color: '#FFFFFF',
        size: 12,
        family: 'Helvetica Neue',
        weight: 'normal',
        borderSize: 1,
        borderColor: '#686D76',
        borderRadius: 2,
        paddingLeft: 4,
        paddingRight: 4,
        paddingTop: 4,
        paddingBottom: 4,
        backgroundColor: '#686D76',
      },
    },
    vertical: {
      show: true,
      line: {
        show: true,
        size: 1,
        color: '#76808F',
      },
      text: {
        show: true,
        color: '#FFFFFF',
        size: 12,
        family: 'Helvetica Neue',
        weight: 'normal',
        borderSize: 1,
        borderColor: '#686D76',
        borderRadius: 2,
        paddingLeft: 4,
        paddingRight: 4,
        paddingTop: 4,
        paddingBottom: 4,
        backgroundColor: '#686D76',
      },
    },
  },
  overlay: {
    point: {
      color: '#1677FF',
      borderColor: 'rgba(22, 119, 255, 0.35)',
      borderSize: 1,
      radius: 5,
      activeColor: '#1677FF',
      activeBorderColor: 'rgba(22, 119, 255, 0.35)',
      activeBorderSize: 3,
      activeRadius: 5,
    },
    line: {
      color: '#1677FF',
      size: 1,
    },
    rect: {
      color: 'rgba(22, 119, 255, 0.25)',
      borderColor: '#1677FF',
      borderSize: 1,
      borderRadius: 0,
    },
    polygon: {
      color: 'rgba(22, 119, 255, 0.25)',
      borderColor: '#1677FF',
      borderSize: 1,
    },
    circle: {
      color: 'rgba(22, 119, 255, 0.25)',
      borderColor: '#1677FF',
      borderSize: 1,
    },
    arc: {
      color: '#1677FF',
      size: 1,
    },
    text: {
      color: '#FFFFFF',
      size: 12,
      family: 'Helvetica Neue',
      weight: 'normal',
      borderSize: 0,
      borderRadius: 2,
      borderColor: '#1677FF',
      paddingLeft: 4,
      paddingRight: 4,
      paddingTop: 4,
      paddingBottom: 4,
      backgroundColor: '#1677FF',
    },
  },
}

export const darkTheme: DeepPartial<Styles> = {
  grid: {
    show: true,
    horizontal: {
      show: true,
      size: 1,
      color: '#292929',
    },
    vertical: {
      show: true,
      size: 1,
      color: '#292929',
    },
  },
  candle: {
    bar: {
      upColor: '#26A69A',
      downColor: '#EF5350',
      noChangeColor: '#888888',
      upBorderColor: '#26A69A',
      downBorderColor: '#EF5350',
      noChangeBorderColor: '#888888',
      upWickColor: '#26A69A',
      downWickColor: '#EF5350',
      noChangeWickColor: '#888888',
    },
    priceMark: {
      show: true,
      high: {
        show: true,
        color: '#929AA5',
        textOffset: 5,
        textSize: 10,
        textFamily: 'Helvetica Neue',
        textWeight: 'normal',
      },
      low: {
        show: true,
        color: '#929AA5',
        textOffset: 5,
        textSize: 10,
        textFamily: 'Helvetica Neue',
        textWeight: 'normal',
      },
      last: {
        show: true,
        upColor: '#26A69A',
        downColor: '#EF5350',
        noChangeColor: '#888888',
        line: {
          show: true,
          size: 1,
        },
        text: {
          show: true,
          size: 12,
          paddingLeft: 4,
          paddingTop: 4,
          paddingRight: 4,
          paddingBottom: 4,
          color: '#FFFFFF',
          family: 'Helvetica Neue',
          weight: 'normal',
          borderRadius: 2,
        },
      },
    },
    tooltip: {
      rect: {
        paddingLeft: 4,
        paddingRight: 4,
        paddingTop: 4,
        paddingBottom: 4,
        offsetLeft: 4,
        offsetTop: 4,
        offsetRight: 4,
        offsetBottom: 4,
        borderRadius: 4,
        borderSize: 1,
        borderColor: '#3D3D3D',
        color: '#1F1F1F',
      },
      legend: {
        defaultValue: 'n/a',
        size: 12,
        family: 'Helvetica Neue',
        weight: 'normal',
        color: '#929AA5',
        marginLeft: 8,
        marginTop: 4,
        marginRight: 8,
        marginBottom: 4,
      },
    },
  },
  indicator: {
    ohlc: {
      upColor: '#26A69A',
      downColor: '#EF5350',
      noChangeColor: '#888888',
    },
    lines: [
      { size: 1, color: '#FF9600' },
      { size: 1, color: '#935EBD' },
      { size: 1, color: '#2196F3' },
      { size: 1, color: '#E11D74' },
      { size: 1, color: '#01C5C4' },
    ],
    tooltip: {
      title: {
        showName: true,
        showParams: true,
      },
      legend: {
        defaultValue: 'n/a',
        size: 12,
        family: 'Helvetica Neue',
        weight: 'normal',
        color: '#929AA5',
        marginLeft: 8,
        marginTop: 4,
        marginRight: 8,
        marginBottom: 4,
      },
    },
  },
  xAxis: {
    show: true,
    axisLine: {
      show: true,
      color: '#3D3D3D',
      size: 1,
    },
    tickText: {
      show: true,
      color: '#929AA5',
      family: 'Helvetica Neue',
      weight: 'normal',
      size: 12,
      marginStart: 4,
      marginEnd: 4,
    },
    tickLine: {
      show: true,
      size: 1,
      length: 3,
      color: '#3D3D3D',
    },
  },
  yAxis: {
    show: true,
    axisLine: {
      show: true,
      color: '#3D3D3D',
      size: 1,
    },
    tickText: {
      show: true,
      color: '#929AA5',
      family: 'Helvetica Neue',
      weight: 'normal',
      size: 12,
      marginStart: 4,
      marginEnd: 4,
    },
    tickLine: {
      show: true,
      size: 1,
      length: 3,
      color: '#3D3D3D',
    },
  },
  separator: {
    size: 1,
    color: '#3D3D3D',
    fill: true,
    activeBackgroundColor: 'rgba(33, 150, 243, 0.08)',
  },
  crosshair: {
    show: true,
    horizontal: {
      show: true,
      line: {
        show: true,
        size: 1,
        color: '#929AA5',
      },
      text: {
        show: true,
        color: '#FFFFFF',
        size: 12,
        family: 'Helvetica Neue',
        weight: 'normal',
        borderSize: 1,
        borderColor: '#686D76',
        borderRadius: 2,
        paddingLeft: 4,
        paddingRight: 4,
        paddingTop: 4,
        paddingBottom: 4,
        backgroundColor: '#686D76',
      },
    },
    vertical: {
      show: true,
      line: {
        show: true,
        size: 1,
        color: '#929AA5',
      },
      text: {
        show: true,
        color: '#FFFFFF',
        size: 12,
        family: 'Helvetica Neue',
        weight: 'normal',
        borderSize: 1,
        borderColor: '#686D76',
        borderRadius: 2,
        paddingLeft: 4,
        paddingRight: 4,
        paddingTop: 4,
        paddingBottom: 4,
        backgroundColor: '#686D76',
      },
    },
  },
  overlay: {
    point: {
      color: '#1677FF',
      borderColor: 'rgba(22, 119, 255, 0.35)',
      borderSize: 1,
      radius: 5,
      activeColor: '#1677FF',
      activeBorderColor: 'rgba(22, 119, 255, 0.35)',
      activeBorderSize: 3,
      activeRadius: 5,
    },
    line: {
      color: '#1677FF',
      size: 1,
    },
    rect: {
      color: 'rgba(22, 119, 255, 0.25)',
      borderColor: '#1677FF',
      borderSize: 1,
      borderRadius: 0,
    },
    polygon: {
      color: 'rgba(22, 119, 255, 0.25)',
      borderColor: '#1677FF',
      borderSize: 1,
    },
    circle: {
      color: 'rgba(22, 119, 255, 0.25)',
      borderColor: '#1677FF',
      borderSize: 1,
    },
    arc: {
      color: '#1677FF',
      size: 1,
    },
    text: {
      color: '#FFFFFF',
      size: 12,
      family: 'Helvetica Neue',
      weight: 'normal',
      borderSize: 0,
      borderRadius: 2,
      borderColor: '#1677FF',
      paddingLeft: 4,
      paddingRight: 4,
      paddingTop: 4,
      paddingBottom: 4,
      backgroundColor: '#1677FF',
    },
  },
}
