kind: pipeline
type: docker
name: exchange-adapter-service


trigger:
  branch:
    - master

volumes:
  - name: go-modules-cache
    host:
      path: /var/lib/drone-cache/go-modules
  - name: app
    host:
      path: /data/app/exchange-adapter-service

steps:
  # 1. 恢复 缓存1
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: go-modules-cache
        path: /cache
    settings:
      restore: true
      cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH ]
      mount:
        - /drone/src/.cache/

  # - name: inject-config
  #   image: appleboy/drone-ssh
  #   settings:
  #     host:
  #       from_secret: CURRENT_HOST
  #     username: root
  #     password:
  #       from_secret: SSH_PWD
  #     port: 22
  #     command_timeout: 2m
  #     script:
  #       - mc cp local/config/exchange-sync/config.prod.yaml /data/app/exchange-sync/config.local.yaml
  #       - cat /data/app/exchange-sync/config.local.yaml

  - name: build
    image: golang:1.24-alpine
    environment:
      GOPROXY: https://goproxy.cn,direct
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
      GOMODCACHE: /drone/src/.cache/mod
      GOCACHE: /drone/src/.cache/build
      API_CONFIG_TOKEN_SECRET:
        from_secret: API_CONFIG_TOKEN_SECRET
    volumes:
      - name: app
        path: /temp/exchange-adapter-service
    commands:
      - APP_NAME=exchange-adapter-service
      - APP_DIR=apps/$APP_NAME
      - echo $API_CONFIG_TOKEN_SECRET
      - mkdir -p /drone/src/.cache/mod
      - go mod download
      - cd $APP_DIR
      - 'wget --header="Authorization: Bearer $API_CONFIG_TOKEN_SECRET" "http://config.8and1.cn/api/pull/exchange-sync/config.prod.yaml" -O config.local.yaml'
      - cat config.local.yaml
      - go build -ldflags="-s -w" -o $APP_NAME ./cmd/main.go
      - tar czf $APP_NAME.tar.gz ./*

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: go-modules-cache
        path: /cache
    settings:
      rebuild: true
      cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH ]
      mount:
        - /drone/src/.cache

  - name: scp
    image: appleboy/drone-scp
    settings:
      debug: true
      source:
        - apps/exchange-adapter-service/exchange-adapter-service.tar.gz
      host:
        from_secret: HOST_HONKONG_1
      username: root
      port: 22
      password:
        from_secret: SSH_PWD
      target: /temp

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: HOST_HONKONG_1
      username: root
      password:
        from_secret: SSH_PWD
      port: 22
      command_timeout: 2m
      script:
        - export APP_NAME=exchange-adapter-service
        - cd /temp/apps/$APP_NAME
        - mkdir -p /data/app/$APP_NAME
        - rm -rf /data/app/$APP_NAME/*
        - tar xzf $APP_NAME.tar.gz -C /data/app/$APP_NAME
        - cd /data/app/$APP_NAME
        - ls -la
        - docker-compose up -d --no-recreate nats redis
        - docker-compose up -d --force-recreate --no-deps exchange-adapter-service
        - sleep 2
        - docker logs exchange-adapter-service
        # - docker logs exchange-adapter-nats

