"""Type stubs for hquant native module."""

from typing import Optional, List

class PyBar:
    """K-line (candlestick) bar data."""

    timestamp: int
    open: float
    high: float
    low: float
    close: float
    volume: float

    def __init__(
        self,
        timestamp: int,
        open: float,
        high: float,
        low: float,
        close: float,
        volume: float,
    ) -> None: ...
    def __repr__(self) -> str: ...

class PySignal:
    """Trading signal output."""

    side: str
    strength: float
    reason: str
    timestamp: int

    @property
    def is_buy(self) -> bool: ...
    @property
    def is_sell(self) -> bool: ...
    @property
    def is_hold(self) -> bool: ...
    def __repr__(self) -> str: ...

class PyIndicatorValue:
    """Indicator result with optional extra data."""

    value: float
    timestamp: int
    extra: Optional[List[float]]

    def __repr__(self) -> str: ...

class PyMABuilder:
    """Moving Average indicator builder."""

    def __init__(self) -> None: ...
    def period(self, period: int) -> PyMABuilder: ...
    def sma(self) -> PyMABuilder: ...
    def ema(self) -> PyMABuilder: ...
    def wma(self) -> PyMABuilder: ...

class PyRSIBuilder:
    """RSI indicator builder."""

    def __init__(self) -> None: ...
    def period(self, period: int) -> PyRSIBuilder: ...

class PyMACDBuilder:
    """MACD indicator builder."""

    def __init__(self) -> None: ...
    def fast(self, period: int) -> PyMACDBuilder: ...
    def slow(self, period: int) -> PyMACDBuilder: ...
    def signal(self, period: int) -> PyMACDBuilder: ...

class PyATRBuilder:
    """ATR indicator builder."""

    def __init__(self) -> None: ...
    def period(self, period: int) -> PyATRBuilder: ...

class PyBOLLBuilder:
    """Bollinger Bands indicator builder."""

    def __init__(self) -> None: ...
    def period(self, period: int) -> PyBOLLBuilder: ...
    def std_dev(self, factor: float) -> PyBOLLBuilder: ...

class PyVRIBuilder:
    """VRI (Volume Relative Index) indicator builder."""

    def __init__(self) -> None: ...
    def period(self, period: int) -> PyVRIBuilder: ...

class PyIndicators:
    """Indicators factory for creating indicator builders."""

    def __init__(self) -> None: ...
    def ma(self) -> PyMABuilder: ...
    def rsi(self) -> PyRSIBuilder: ...
    def macd(self) -> PyMACDBuilder: ...
    def atr(self) -> PyATRBuilder: ...
    def boll(self) -> PyBOLLBuilder: ...
    def vri(self) -> PyVRIBuilder: ...

class PyBacktestConfig:
    """Backtest configuration."""

    market_type: str
    initial_capital: float
    leverage: float
    maker_fee: float
    taker_fee: float
    slippage: float
    position_size_pct: float

    def __init__(
        self,
        initial_capital: float = 10000.0,
        market_type: str = "spot",
        leverage: float = 1.0,
        maker_fee: float = 0.001,
        taker_fee: float = 0.001,
        slippage: float = 0.0005,
        position_size_pct: float = 0.1,
    ) -> None: ...
    @staticmethod
    def spot(initial_capital: float) -> PyBacktestConfig: ...
    @staticmethod
    def futures(initial_capital: float, leverage: float) -> PyBacktestConfig: ...

class PyBacktestStats:
    """Backtest statistics result."""

    total_trades: int
    winning_trades: int
    losing_trades: int
    total_pnl: float
    max_drawdown: float
    max_drawdown_pct: float
    sharpe_ratio: float
    win_rate: float
    profit_factor: float
    final_equity: float
    return_pct: float
    liquidations: int

    def __repr__(self) -> str: ...

class PyTrade:
    """Trade record."""

    timestamp: int
    side: str
    price: float
    size: float
    fee: float
    pnl: float

    def __repr__(self) -> str: ...

class PyPosition:
    """Current position."""

    side: str
    size: float
    entry_price: float
    leverage: float
    liquidation_price: float
    unrealized_pnl: float
    timestamp: int

    def __repr__(self) -> str: ...

class PyAggregator:
    """K-line aggregator for a single target timeframe."""

    def __init__(self, source_tf: str, target_tf: str, capacity: int) -> None: ...
    def push(self, bar: PyBar) -> bool: ...
    def update_last(self, bar: PyBar) -> None: ...
    def current(self) -> Optional[PyBar]: ...
    def output(self) -> List[PyBar]: ...
    def flush(self) -> Optional[PyBar]: ...

class PyMultiTimeFrameAggregator:
    """Multi-timeframe K-line aggregator."""

    def __init__(self, base_tf: str, target_tfs: List[str], capacity: int) -> None: ...
    def push(self, bar: PyBar) -> List[str]: ...
    def output(self, tf: str) -> List[PyBar]: ...
    def current(self, tf: str) -> Optional[PyBar]: ...

class PyQuantEngine:
    """Main quantitative trading engine (internal)."""

    def __init__(self, capacity: int) -> None: ...

    # Indicator management (unified method pattern)
    def add_ma_indicator(self, name: str, indicator: PyMABuilder) -> None: ...
    def add_rsi_indicator(self, name: str, indicator: PyRSIBuilder) -> None: ...
    def add_macd_indicator(self, name: str, indicator: PyMACDBuilder) -> None: ...
    def add_atr_indicator(self, name: str, indicator: PyATRBuilder) -> None: ...
    def add_boll_indicator(self, name: str, indicator: PyBOLLBuilder) -> None: ...
    def add_vri_indicator(self, name: str, indicator: PyVRIBuilder) -> None: ...
    def add_vwap_indicator(self, name: str) -> None: ...
    def add_obv_indicator(self, name: str) -> None: ...
    def add_mfi_indicator(self, name: str, period: int) -> None: ...
    def add_williams_r_indicator(self, name: str, period: int) -> None: ...
    def add_cci_indicator(self, name: str, period: int) -> None: ...
    def add_roc_indicator(self, name: str, period: int) -> None: ...

    # Multi-timeframe aggregation
    def setup_aggregator(
        self, base_tf: str, target_tfs: List[str], capacity: int
    ) -> None: ...

    # Backtesting
    def setup_backtest(self, config: PyBacktestConfig) -> None: ...
    def backtest_result(self) -> Optional[PyBacktestStats]: ...
    def backtest_trades(self) -> List[PyTrade]: ...
    def backtest_equity_curve(self) -> List[float]: ...

    # Data processing
    def append_bar(self, bar: PyBar) -> List[PySignal]: ...
    def update_last_bar(self, bar: PyBar) -> None: ...
    def load_history(self, bars: List[PyBar]) -> List[PySignal]: ...

    # Indicator access
    def indicator_value(self, name: str) -> Optional[float]: ...
    def indicator_result(self, name: str) -> Optional[PyIndicatorValue]: ...
    def indicator_ready(self, name: str) -> bool: ...

    # Data access
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def last_bar(self) -> Optional[PyBar]: ...

    # Management
    def reset(self) -> None: ...

class PyBacktestEngine:
    """Standalone backtest engine for custom strategy execution."""

    def __init__(self, config: PyBacktestConfig) -> None: ...
    def process_signal(self, side: str, strength: float, bar: PyBar) -> None: ...
    def position(self) -> Optional[PyPosition]: ...
    def equity(self) -> float: ...
    def result(self) -> PyBacktestStats: ...
    def trades(self) -> List[PyTrade]: ...
    def equity_curve(self) -> List[float]: ...
    def reset(self) -> None: ...
