// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: symbol_info.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSymbolInfo = `-- name: DeleteSymbolInfo :exec
DELETE FROM symbol_infos
WHERE
    exchange = $1
    AND symbol = $2
    AND trade_type = $3
`

type DeleteSymbolInfoParams struct {
	Exchange  string `db:"exchange" json:"exchange"`
	Symbol    string `db:"symbol" json:"symbol"`
	TradeType string `db:"trade_type" json:"trade_type"`
}

// Delete a symbol and return for unsubscribe handling
func (q *Queries) DeleteSymbolInfo(ctx context.Context, arg DeleteSymbolInfoParams) error {
	_, err := q.db.Exec(ctx, deleteSymbolInfo, arg.Exchange, arg.Symbol, arg.TradeType)
	return err
}

const deleteSymbolInfosByExchange = `-- name: DeleteSymbolInfosByExchange :exec
DELETE FROM symbol_infos WHERE exchange = $1 AND trade_type = $2
`

type DeleteSymbolInfosByExchangeParams struct {
	Exchange  string `db:"exchange" json:"exchange"`
	TradeType string `db:"trade_type" json:"trade_type"`
}

// Delete all symbols for an exchange and trade type
func (q *Queries) DeleteSymbolInfosByExchange(ctx context.Context, arg DeleteSymbolInfosByExchangeParams) error {
	_, err := q.db.Exec(ctx, deleteSymbolInfosByExchange, arg.Exchange, arg.TradeType)
	return err
}

const getSymbolInfo = `-- name: GetSymbolInfo :one
SELECT
    symbol,
    raw_symbol,
    base_currency,
    quote_currency,
    trade_type,
    COALESCE(tick_size, '') as tick_size,
    COALESCE(step_size, '') as step_size,
    COALESCE(min_qty, '') as min_qty,
    COALESCE(max_qty, '') as max_qty,
    COALESCE(quantity_precision, 0) as quantity_precision,
    COALESCE(price_precision, 0) as price_precision,
    COALESCE(status, '') as status,
    contract_value,
    max_leverage,
    COALESCE(sync_enabled, true) as sync_enabled
FROM symbol_infos
WHERE
    exchange = $1
    AND symbol = $2
    AND trade_type = $3
`

type GetSymbolInfoParams struct {
	Exchange  string `db:"exchange" json:"exchange"`
	Symbol    string `db:"symbol" json:"symbol"`
	TradeType string `db:"trade_type" json:"trade_type"`
}

type GetSymbolInfoRow struct {
	Symbol            string         `db:"symbol" json:"symbol"`
	RawSymbol         string         `db:"raw_symbol" json:"raw_symbol"`
	BaseCurrency      string         `db:"base_currency" json:"base_currency"`
	QuoteCurrency     string         `db:"quote_currency" json:"quote_currency"`
	TradeType         string         `db:"trade_type" json:"trade_type"`
	TickSize          string         `db:"tick_size" json:"tick_size"`
	StepSize          string         `db:"step_size" json:"step_size"`
	MinQty            string         `db:"min_qty" json:"min_qty"`
	MaxQty            string         `db:"max_qty" json:"max_qty"`
	QuantityPrecision int32          `db:"quantity_precision" json:"quantity_precision"`
	PricePrecision    int32          `db:"price_precision" json:"price_precision"`
	Status            string         `db:"status" json:"status"`
	ContractValue     pgtype.Numeric `db:"contract_value" json:"contract_value"`
	MaxLeverage       pgtype.Numeric `db:"max_leverage" json:"max_leverage"`
	SyncEnabled       bool           `db:"sync_enabled" json:"sync_enabled"`
}

func (q *Queries) GetSymbolInfo(ctx context.Context, arg GetSymbolInfoParams) (GetSymbolInfoRow, error) {
	row := q.db.QueryRow(ctx, getSymbolInfo, arg.Exchange, arg.Symbol, arg.TradeType)
	var i GetSymbolInfoRow
	err := row.Scan(
		&i.Symbol,
		&i.RawSymbol,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.TradeType,
		&i.TickSize,
		&i.StepSize,
		&i.MinQty,
		&i.MaxQty,
		&i.QuantityPrecision,
		&i.PricePrecision,
		&i.Status,
		&i.ContractValue,
		&i.MaxLeverage,
		&i.SyncEnabled,
	)
	return i, err
}

const getSymbolInfoByKey = `-- name: GetSymbolInfoByKey :one
SELECT
    id,
    exchange,
    symbol,
    raw_symbol,
    base_currency,
    quote_currency,
    trade_type,
    COALESCE(tick_size, '') as tick_size,
    COALESCE(step_size, '') as step_size,
    COALESCE(min_qty, '') as min_qty,
    COALESCE(max_qty, '') as max_qty,
    COALESCE(quantity_precision, 0) as quantity_precision,
    COALESCE(price_precision, 0) as price_precision,
    COALESCE(status, '') as status,
    contract_value,
    max_leverage,
    COALESCE(sync_enabled, true) as sync_enabled
FROM symbol_infos
WHERE
    exchange = $1
    AND symbol = $2
    AND trade_type = $3
`

type GetSymbolInfoByKeyParams struct {
	Exchange  string `db:"exchange" json:"exchange"`
	Symbol    string `db:"symbol" json:"symbol"`
	TradeType string `db:"trade_type" json:"trade_type"`
}

type GetSymbolInfoByKeyRow struct {
	ID                int64          `db:"id" json:"id"`
	Exchange          string         `db:"exchange" json:"exchange"`
	Symbol            string         `db:"symbol" json:"symbol"`
	RawSymbol         string         `db:"raw_symbol" json:"raw_symbol"`
	BaseCurrency      string         `db:"base_currency" json:"base_currency"`
	QuoteCurrency     string         `db:"quote_currency" json:"quote_currency"`
	TradeType         string         `db:"trade_type" json:"trade_type"`
	TickSize          string         `db:"tick_size" json:"tick_size"`
	StepSize          string         `db:"step_size" json:"step_size"`
	MinQty            string         `db:"min_qty" json:"min_qty"`
	MaxQty            string         `db:"max_qty" json:"max_qty"`
	QuantityPrecision int32          `db:"quantity_precision" json:"quantity_precision"`
	PricePrecision    int32          `db:"price_precision" json:"price_precision"`
	Status            string         `db:"status" json:"status"`
	ContractValue     pgtype.Numeric `db:"contract_value" json:"contract_value"`
	MaxLeverage       pgtype.Numeric `db:"max_leverage" json:"max_leverage"`
	SyncEnabled       bool           `db:"sync_enabled" json:"sync_enabled"`
}

// Get single symbol info
func (q *Queries) GetSymbolInfoByKey(ctx context.Context, arg GetSymbolInfoByKeyParams) (GetSymbolInfoByKeyRow, error) {
	row := q.db.QueryRow(ctx, getSymbolInfoByKey, arg.Exchange, arg.Symbol, arg.TradeType)
	var i GetSymbolInfoByKeyRow
	err := row.Scan(
		&i.ID,
		&i.Exchange,
		&i.Symbol,
		&i.RawSymbol,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.TradeType,
		&i.TickSize,
		&i.StepSize,
		&i.MinQty,
		&i.MaxQty,
		&i.QuantityPrecision,
		&i.PricePrecision,
		&i.Status,
		&i.ContractValue,
		&i.MaxLeverage,
		&i.SyncEnabled,
	)
	return i, err
}

const getSymbolInfos = `-- name: GetSymbolInfos :many
SELECT
    symbol,
    raw_symbol,
    base_currency,
    quote_currency,
    trade_type,
    COALESCE(tick_size, '') as tick_size,
    COALESCE(step_size, '') as step_size,
    COALESCE(min_qty, '') as min_qty,
    COALESCE(max_qty, '') as max_qty,
    COALESCE(quantity_precision, 0) as quantity_precision,
    COALESCE(price_precision, 0) as price_precision,
    COALESCE(status, '') as status,
    contract_value,
    max_leverage,
    COALESCE(sync_enabled, true) as sync_enabled
FROM symbol_infos
WHERE
    exchange = $1
ORDER BY symbol
`

type GetSymbolInfosRow struct {
	Symbol            string         `db:"symbol" json:"symbol"`
	RawSymbol         string         `db:"raw_symbol" json:"raw_symbol"`
	BaseCurrency      string         `db:"base_currency" json:"base_currency"`
	QuoteCurrency     string         `db:"quote_currency" json:"quote_currency"`
	TradeType         string         `db:"trade_type" json:"trade_type"`
	TickSize          string         `db:"tick_size" json:"tick_size"`
	StepSize          string         `db:"step_size" json:"step_size"`
	MinQty            string         `db:"min_qty" json:"min_qty"`
	MaxQty            string         `db:"max_qty" json:"max_qty"`
	QuantityPrecision int32          `db:"quantity_precision" json:"quantity_precision"`
	PricePrecision    int32          `db:"price_precision" json:"price_precision"`
	Status            string         `db:"status" json:"status"`
	ContractValue     pgtype.Numeric `db:"contract_value" json:"contract_value"`
	MaxLeverage       pgtype.Numeric `db:"max_leverage" json:"max_leverage"`
	SyncEnabled       bool           `db:"sync_enabled" json:"sync_enabled"`
}

func (q *Queries) GetSymbolInfos(ctx context.Context, exchange string) ([]GetSymbolInfosRow, error) {
	rows, err := q.db.Query(ctx, getSymbolInfos, exchange)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSymbolInfosRow{}
	for rows.Next() {
		var i GetSymbolInfosRow
		if err := rows.Scan(
			&i.Symbol,
			&i.RawSymbol,
			&i.BaseCurrency,
			&i.QuoteCurrency,
			&i.TradeType,
			&i.TickSize,
			&i.StepSize,
			&i.MinQty,
			&i.MaxQty,
			&i.QuantityPrecision,
			&i.PricePrecision,
			&i.Status,
			&i.ContractValue,
			&i.MaxLeverage,
			&i.SyncEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncEnabledSymbolInfos = `-- name: GetSyncEnabledSymbolInfos :many
SELECT
    symbol,
    raw_symbol,
    base_currency,
    quote_currency,
    trade_type,
    COALESCE(tick_size, '') as tick_size,
    COALESCE(step_size, '') as step_size,
    COALESCE(min_qty, '') as min_qty,
    COALESCE(max_qty, '') as max_qty,
    COALESCE(quantity_precision, 0) as quantity_precision,
    COALESCE(price_precision, 0) as price_precision,
    COALESCE(status, '') as status,
    contract_value,
    max_leverage,
    COALESCE(sync_enabled, true) as sync_enabled
FROM symbol_infos
WHERE
    exchange = $1
    AND COALESCE(sync_enabled, true) = true
ORDER BY symbol
`

type GetSyncEnabledSymbolInfosRow struct {
	Symbol            string         `db:"symbol" json:"symbol"`
	RawSymbol         string         `db:"raw_symbol" json:"raw_symbol"`
	BaseCurrency      string         `db:"base_currency" json:"base_currency"`
	QuoteCurrency     string         `db:"quote_currency" json:"quote_currency"`
	TradeType         string         `db:"trade_type" json:"trade_type"`
	TickSize          string         `db:"tick_size" json:"tick_size"`
	StepSize          string         `db:"step_size" json:"step_size"`
	MinQty            string         `db:"min_qty" json:"min_qty"`
	MaxQty            string         `db:"max_qty" json:"max_qty"`
	QuantityPrecision int32          `db:"quantity_precision" json:"quantity_precision"`
	PricePrecision    int32          `db:"price_precision" json:"price_precision"`
	Status            string         `db:"status" json:"status"`
	ContractValue     pgtype.Numeric `db:"contract_value" json:"contract_value"`
	MaxLeverage       pgtype.Numeric `db:"max_leverage" json:"max_leverage"`
	SyncEnabled       bool           `db:"sync_enabled" json:"sync_enabled"`
}

// Get symbols with sync_enabled = true for WS subscription
func (q *Queries) GetSyncEnabledSymbolInfos(ctx context.Context, exchange string) ([]GetSyncEnabledSymbolInfosRow, error) {
	rows, err := q.db.Query(ctx, getSyncEnabledSymbolInfos, exchange)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSyncEnabledSymbolInfosRow{}
	for rows.Next() {
		var i GetSyncEnabledSymbolInfosRow
		if err := rows.Scan(
			&i.Symbol,
			&i.RawSymbol,
			&i.BaseCurrency,
			&i.QuoteCurrency,
			&i.TradeType,
			&i.TickSize,
			&i.StepSize,
			&i.MinQty,
			&i.MaxQty,
			&i.QuantityPrecision,
			&i.PricePrecision,
			&i.Status,
			&i.ContractValue,
			&i.MaxLeverage,
			&i.SyncEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSymbolSyncEnabled = `-- name: UpdateSymbolSyncEnabled :exec
UPDATE symbol_infos
SET
    sync_enabled = $4,
    updated_at = NOW()
WHERE
    exchange = $1
    AND symbol = $2
    AND trade_type = $3
`

type UpdateSymbolSyncEnabledParams struct {
	Exchange    string      `db:"exchange" json:"exchange"`
	Symbol      string      `db:"symbol" json:"symbol"`
	TradeType   string      `db:"trade_type" json:"trade_type"`
	SyncEnabled pgtype.Bool `db:"sync_enabled" json:"sync_enabled"`
}

// Update sync_enabled flag for a symbol
func (q *Queries) UpdateSymbolSyncEnabled(ctx context.Context, arg UpdateSymbolSyncEnabledParams) error {
	_, err := q.db.Exec(ctx, updateSymbolSyncEnabled,
		arg.Exchange,
		arg.Symbol,
		arg.TradeType,
		arg.SyncEnabled,
	)
	return err
}

const upsertSymbolInfo = `-- name: UpsertSymbolInfo :exec
INSERT INTO
    symbol_infos (
        exchange,
        symbol,
        raw_symbol,
        base_currency,
        quote_currency,
        trade_type,
        tick_size,
        step_size,
        min_qty,
        max_qty,
        quantity_precision,
        price_precision,
        status,
        contract_value,
        max_leverage
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15
    ) ON CONFLICT (exchange, symbol, trade_type) DO
UPDATE
SET
    raw_symbol = EXCLUDED.raw_symbol,
    tick_size = EXCLUDED.tick_size,
    step_size = EXCLUDED.step_size,
    min_qty = EXCLUDED.min_qty,
    max_qty = EXCLUDED.max_qty,
    quantity_precision = EXCLUDED.quantity_precision,
    price_precision = EXCLUDED.price_precision,
    status = EXCLUDED.status,
    contract_value = EXCLUDED.contract_value,
    max_leverage = EXCLUDED.max_leverage,
    updated_at = NOW()
`

type UpsertSymbolInfoParams struct {
	Exchange          string         `db:"exchange" json:"exchange"`
	Symbol            string         `db:"symbol" json:"symbol"`
	RawSymbol         string         `db:"raw_symbol" json:"raw_symbol"`
	BaseCurrency      string         `db:"base_currency" json:"base_currency"`
	QuoteCurrency     string         `db:"quote_currency" json:"quote_currency"`
	TradeType         string         `db:"trade_type" json:"trade_type"`
	TickSize          pgtype.Text    `db:"tick_size" json:"tick_size"`
	StepSize          pgtype.Text    `db:"step_size" json:"step_size"`
	MinQty            pgtype.Text    `db:"min_qty" json:"min_qty"`
	MaxQty            pgtype.Text    `db:"max_qty" json:"max_qty"`
	QuantityPrecision pgtype.Int4    `db:"quantity_precision" json:"quantity_precision"`
	PricePrecision    pgtype.Int4    `db:"price_precision" json:"price_precision"`
	Status            pgtype.Text    `db:"status" json:"status"`
	ContractValue     pgtype.Numeric `db:"contract_value" json:"contract_value"`
	MaxLeverage       pgtype.Numeric `db:"max_leverage" json:"max_leverage"`
}

// Insert new symbol or update existing (without overwriting symbol, base_currency, quote_currency)
func (q *Queries) UpsertSymbolInfo(ctx context.Context, arg UpsertSymbolInfoParams) error {
	_, err := q.db.Exec(ctx, upsertSymbolInfo,
		arg.Exchange,
		arg.Symbol,
		arg.RawSymbol,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.TradeType,
		arg.TickSize,
		arg.StepSize,
		arg.MinQty,
		arg.MaxQty,
		arg.QuantityPrecision,
		arg.PricePrecision,
		arg.Status,
		arg.ContractValue,
		arg.MaxLeverage,
	)
	return err
}
